---
title: R class home work
author: Feng Yuqi
date: '2021-05-28'
slug: r-class-home-work
categories:
  - R
tags: [homework]
output: 
  html_document: 
    toc: yes
    highlight: espresso
    number_sections: yes
---

<script src="{{< blogdown/postref >}}index_files/header-attrs/header-attrs.js"></script>
<link href="{{< blogdown/postref >}}index_files/pagedtable/css/pagedtable.css" rel="stylesheet" />
<script src="{{< blogdown/postref >}}index_files/pagedtable/js/pagedtable.js"></script>


<p>这里由于还没有搞清楚具体的实施方案所以后五次作业还未上传。</p>
<div id="第一次作业" class="section level1">
<h1>第一次作业</h1>
<div id="第一题" class="section level2">
<h2>第一题</h2>
<pre class="r"><code>help(stem)</code></pre>
<pre><code>## starting httpd help server ... done</code></pre>
<pre class="r"><code>data5&lt;-c(12, 12, 11, 10, 9, 10, 12)
stem(data5)</code></pre>
<pre><code>## 
##   The decimal point is at the |
## 
##    9 | 0
##   10 | 00
##   11 | 0
##   12 | 000</code></pre>
</div>
<div id="第二题" class="section level2">
<h2>第二题</h2>
<pre class="r"><code>x &lt;- ((0:10000)/10000)*2*pi
y &lt;- x^3 + sin(x)*cos(x)
plot(x, y, col=&quot;blue&quot;, type=&quot;l&quot;, xlab=&quot;自变量X&quot;, ylab=&quot;函数Y&quot;, main=&quot;示意图&quot;)</code></pre>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-2-1.png" width="672" /></p>
</div>
</div>
<div id="第二次作业" class="section level1">
<h1>第二次作业</h1>
<div id="第一题-1" class="section level2">
<h2>第一题</h2>
<p>1.随机变量<span class="math inline">\(X~B(10,0.4)\)</span>,求分布律和分布函数，求<span class="math inline">\(P(X=3)\)</span>
解：</p>
<pre class="r"><code>x&lt;-0:20
(y&lt;-dbinom(x,10,0.4))#分布律</code></pre>
<pre><code>##  [1] 0.0060466176 0.0403107840 0.1209323520 0.2149908480 0.2508226560
##  [6] 0.2006581248 0.1114767360 0.0424673280 0.0106168320 0.0015728640
## [11] 0.0001048576 0.0000000000 0.0000000000 0.0000000000 0.0000000000
## [16] 0.0000000000 0.0000000000 0.0000000000 0.0000000000 0.0000000000
## [21] 0.0000000000</code></pre>
<pre class="r"><code>(pbinom(x,10,0.4))#分布函数</code></pre>
<pre><code>##  [1] 0.006046618 0.046357402 0.167289754 0.382280602 0.633103258 0.833761382
##  [7] 0.945238118 0.987705446 0.998322278 0.999895142 1.000000000 1.000000000
## [13] 1.000000000 1.000000000 1.000000000 1.000000000 1.000000000 1.000000000
## [19] 1.000000000 1.000000000 1.000000000</code></pre>
<p>求<span class="math inline">\(P(X=3)\)</span></p>
<pre class="r"><code>(pbinom(3,10,0.4))</code></pre>
<pre><code>## [1] 0.3822806</code></pre>
</div>
<div id="第二题-1" class="section level2">
<h2>第二题</h2>
<p>随机变量<span class="math inline">\(X\)</span>服从1到5的离散均匀分布，求<span class="math inline">\(P(1&lt;X&lt;3)\)</span></p>
<pre class="r"><code>(punif(3,1,5)-punif(1,1,5))</code></pre>
<pre><code>## [1] 0.5</code></pre>
</div>
<div id="第三题" class="section level2">
<h2>第三题</h2>
<p>随机变量<span class="math inline">\(X~U(2,4)\)</span>,画出密度函数和分布函数，求<span class="math inline">\(P(2.5&lt;X&lt;3.5)\)</span></p>
<pre class="r"><code>x&lt;-seq(0,8,0.01)
y&lt;-dunif(x,2,4)
z&lt;-punif(x,2,4)
data1&lt;-data.frame(a=x,b=y,c=z)
#g&lt;-ggplot(data = data1,aes(x=a,y=b),col=&quot;red&quot;)+geom_line()
library(ggplot2)
ggplot()+geom_line(data=data1,aes(x=a,y=c),col=&quot;blue&quot;)+geom_line(data = data1,aes(x=a,y=b),col=&quot;red&quot;)</code></pre>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-6-1.png" width="672" /></p>
<pre class="r"><code>(punif(3.5,2,4)-punif(2.5,2,4))</code></pre>
<pre><code>## [1] 0.5</code></pre>
</div>
<div id="第四题" class="section level2">
<h2>第四题</h2>
<p>随机变量<span class="math inline">\(X~E(4)\)</span>画出密度函数和分布函数，求<span class="math inline">\(P(1&lt;X&lt;5)\)</span></p>
<pre class="r"><code>x&lt;-seq(0,5,0.5)
y&lt;-dexp(x,4)
z&lt;-pexp(x,4)
plot(x,z,type = &quot;l&quot;,col=&quot;blue&quot;)
lines(x,y,type =&quot;l&quot;,col=&quot;red&quot;)</code></pre>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-8-1.png" width="672" /></p>
<pre class="r"><code>(pexp(5,4)-pexp(1,4))</code></pre>
<pre><code>## [1] 0.01831564</code></pre>
</div>
<div id="第五题" class="section level2">
<h2>第五题</h2>
<pre class="r"><code>x&lt;-seq(-5,5,0.01)
y&lt;-dnorm(x,1,2)
z&lt;-pnorm(x,1,2)
plot(x,y,type = &quot;l&quot;,col=&quot;red&quot;)
lines(x,z,type=&quot;l&quot;,col=&quot;blue&quot;)</code></pre>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-10-1.png" width="672" /></p>
<pre class="r"><code>(pnorm(3,1,2)-pnorm(-2,1,2))</code></pre>
<pre><code>## [1] 0.7745375</code></pre>
</div>
</div>
<div id="第三次作业" class="section level1">
<h1>第三次作业</h1>
<div id="第一题-2" class="section level2">
<h2>第一题</h2>
<pre class="r"><code>#help(tapply)
data7&lt;-data.frame(name = c(&quot;jack&quot;,&quot;rose&quot;,&quot;mike&quot;),age = c(5,6,7),score = c(60,80,90))
aver&lt;-tapply(data7$score,data7$age,mean)
aver</code></pre>
<pre><code>##  5  6  7 
## 60 80 90</code></pre>
</div>
<div id="第二题-2" class="section level2">
<h2>第二题</h2>
<pre class="r"><code>data8&lt;-read.table(file= &quot;D:/rclasstongjiruanjian/user.txt&quot;,header = T)</code></pre>
<pre class="r"><code>table(data8[,2])</code></pre>
<pre><code>## 
##  F  M 
##  9 10</code></pre>
<pre class="r"><code>table(data8[,3])</code></pre>
<pre><code>## 
## 11 12 13 14 15 16 
##  2  5  3  4  4  1</code></pre>
<pre class="r"><code>d&lt;-tapply(data8[,4],data8[,2],mean)
d</code></pre>
<pre><code>##        F        M 
## 60.58889 63.91000</code></pre>
<pre class="r"><code>e&lt;-tapply(data8[,4],data8[,3],mean)
e</code></pre>
<pre><code>##       11       12       13       14       15       16 
## 54.40000 59.44000 61.43333 64.90000 65.62500 72.00000</code></pre>
<pre class="r"><code>list&lt;-list(sexcount=table(data8[,2]),agecount = table(data8[,3]),sexheight = d,ageheight = e)
list</code></pre>
<pre><code>## $sexcount
## 
##  F  M 
##  9 10 
## 
## $agecount
## 
## 11 12 13 14 15 16 
##  2  5  3  4  4  1 
## 
## $sexheight
##        F        M 
## 60.58889 63.91000 
## 
## $ageheight
##       11       12       13       14       15       16 
## 54.40000 59.44000 61.43333 64.90000 65.62500 72.00000</code></pre>
</div>
<div id="第三题-1" class="section level2">
<h2>第三题</h2>
<pre class="r"><code>q&lt;-rnorm(100,0,1)
juzhen&lt;-matrix(q,5,20)
juzhen</code></pre>
<pre><code>##            [,1]        [,2]       [,3]       [,4]        [,5]       [,6]
## [1,]  1.5986562  0.30706179 -0.1007051  0.8483531  0.06638324 -0.5298676
## [2,] -0.3581486  1.97126697  0.4216181  1.4305401 -1.52644143 -2.2966440
## [3,] -1.5189005 -0.23914437 -0.5018847  0.3364413  1.43585825  0.1200956
## [4,]  2.5078224 -0.04351416 -0.2460952 -0.7944763  0.50331543 -0.4103107
## [5,] -1.2820549 -1.91739324 -1.7046170 -1.7517257  0.62260580 -0.5075274
##             [,7]       [,8]        [,9]      [,10]      [,11]      [,12]
## [1,] -0.74443046  0.9086036 -0.37306092  1.7876926  0.9790418  0.7291389
## [2,]  0.33059016 -0.5551763  0.88875684  0.8272038  1.2917029 -0.7235849
## [3,] -1.42660959  2.4850482  0.11616118  0.8672004 -0.0896518  0.1030129
## [4,]  0.08865374  0.7419789  2.53191605  0.1761840 -0.5018744 -0.1971965
## [5,]  0.94713663  0.6526863 -0.08804171 -0.6228922  2.0188305  0.5249277
##           [,13]       [,14]       [,15]      [,16]      [,17]      [,18]
## [1,] -1.2371429  1.09028585 -1.34780318 -1.1959029 -0.6514890  0.7002292
## [2,] -1.7600375  0.02826079 -0.04768925  0.7244111  0.2583115  0.9247852
## [3,]  0.9720902 -1.40024185 -1.25591583 -0.7060724  0.2741938 -0.6491607
## [4,]  0.1911341  0.50819406 -0.88966257 -1.4753059 -1.4796076  0.2709893
## [5,]  0.0694099  0.46707881 -0.16562858 -0.4809066  0.7544185 -1.5929476
##           [,19]      [,20]
## [1,] -0.4807801 -1.7424240
## [2,] -0.8642800  0.6011741
## [3,]  0.4939659 -1.1315631
## [4,] -0.8525664  1.8595967
## [5,]  1.3993939 -0.8192179</code></pre>
<pre class="r"><code>write.table(as.vector(juzhen),file=&quot;juzhen.txt&quot;)
w&lt;-read.table(&quot;juzhen.txt&quot;)
y&lt;-matrix(t(w),5,20)</code></pre>
</div>
<div id="第四题-1" class="section level2">
<h2>第四题</h2>
<pre class="r"><code>t&lt;-0
for( i in 1:100)
    t&lt;-(t+1/i)
    print(t)</code></pre>
<pre><code>## [1] 5.187378</code></pre>
</div>
</div>
<div id="第四次作业" class="section level1">
<h1>第四次作业</h1>
<div id="课后第一题" class="section level2">
<h2>课后第一题</h2>
<pre class="r"><code>findmax &lt;- function(x){
  p&lt;-which(x==x[which.max(x)],arr.ind = T)
  list(maxvalue = x[p],location=which(x==x[which.max(x)],arr.ind = T))
}
A = matrix(floor(rnorm(100,0,4)),4,25)
findmax(A)</code></pre>
<pre><code>## $maxvalue
## [1] 8 8 8
## 
## $location
##      row col
## [1,]   4   7
## [2,]   1   9
## [3,]   2  19</code></pre>
</div>
<div id="作业第二题" class="section level2">
<h2>作业第二题</h2>
<pre class="r"><code>test&lt;-function(x,y){
  p&lt;-(x^2+sin(x*y)+2*y)
  return(p)
}</code></pre>
</div>
<div id="第三节课第三题" class="section level2">
<h2>第三节课第三题</h2>
<pre class="r"><code>fillna&lt;-function(a){
  m&lt;-which(is.na(a),arr.ind = T)
  a[m]&lt;-c(rep(mean(a,na.rm =TRUE),nrow(m)))
  return(a)
  
}
A=matrix(floor(rnorm(100,0,4)),4,25)
A[2,5]=NA; A[4,8]=NA; A[3,15]=NA
fillna(A)</code></pre>
<pre><code>##      [,1] [,2] [,3] [,4]        [,5] [,6] [,7]        [,8] [,9] [,10] [,11]
## [1,]    4    2    5   -6  4.00000000   -2   -1  0.00000000    3     8    -2
## [2,]   -4    0    3   -3  0.01030928    3    3 -6.00000000   -9    -2    -4
## [3,]   -3    3    6   -1  0.00000000    6   -3 -2.00000000    3     1     5
## [4,]   -1   -3    1   -2 -6.00000000   -2   -6  0.01030928    9    -3     5
##      [,12] [,13] [,14]       [,15] [,16] [,17] [,18] [,19] [,20] [,21] [,22]
## [1,]    -4    -6    -5 -1.00000000     1     3    -4     2    -6     9     6
## [2,]    -5     2     5 -3.00000000    -3     5    -1     3    -2     3    -1
## [3,]     6     1     0  0.01030928    -4     1   -14     4     1     3    -3
## [4,]    -1     5    -6  0.00000000    -4     6    -3     1    -3     0    -3
##      [,23] [,24] [,25]
## [1,]     5     4    -2
## [2,]    -1    -5     4
## [3,]     3    -1     0
## [4,]     1     1     4</code></pre>
</div>
<div id="第三节课第四题" class="section level2">
<h2>第三节课第四题</h2>
<pre class="r"><code>fzero&lt;-function(f, a, b, eps=1e-5){
  if   (f(a)*f(b)&gt;0)
    list (fail=&quot;finding root is fail!&quot;)
  else {repeat { 
    if (abs(b-a)&lt;eps)   break
    x&lt;-(a+b)/2
    if  (f(a)*f(b)&lt;0)  b&lt;-x else a&lt;-x
  }
    list(root=(a+b)/2, fun=f(x))
  }
}
f&lt;-function(x) {x^3-x-1}  
fzero(f,1,2,1e-5)</code></pre>
<pre><code>## $root
## [1] 1.249996
## 
## $fun
## [1] -0.2969031</code></pre>
</div>
</div>
<div id="第五次作业" class="section level1">
<h1>第五次作业</h1>
<pre class="r"><code>data &lt;- read.table(&quot;cl.txt&quot;, header=TRUE)
names(data) &lt;- c(&quot;name&quot;, &quot;age&quot;, &quot;height&quot;, &quot;weight&quot;, &quot;sex&quot;)
plot(data$height, data$weight, main=&quot;Regression on Height and Weight&quot;,
     xlab=&quot;Height&quot;, ylab=&quot;Weight&quot;)  </code></pre>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-23-1.png" width="672" /></p>
<pre class="r"><code>par(mfrow=c(2, 2))
qqnorm(data$weight)
hist(data$weight)
boxplot(data$weight) 
qqplot(data$height, data$weight, main=&quot;QQPLOT&quot;, xlab=&quot;Height&quot;, ylab=&quot;Weight&quot;)</code></pre>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-23-2.png" width="672" /></p>
<div id="第二题-3" class="section level2">
<h2>第二题</h2>
<pre class="r"><code>data &lt;- read.table(&quot;cl.txt&quot;, header=TRUE)
plot(data)</code></pre>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-24-1.png" width="672" /></p>
<pre class="r"><code>#coplot(data$Weight~data$Height|data$sex)
pairs(data[,c(&quot;Age&quot;, &quot;Weight&quot;, &quot;Height&quot;)])</code></pre>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-24-2.png" width="672" /></p>
<pre class="r"><code>x &lt;- data.frame(x1=rnorm(72, 0, 1),
             x2=rnorm(72, 0, 1),
             x3=rnorm(72, 0, 1),
             x4=rnorm(72, 0, 1)) 
t &lt;- ts(x, start=c(2015, 1), frequency=12)
plot(t)</code></pre>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-24-3.png" width="672" /></p>
<pre class="r"><code>plot(x[,&quot;x1&quot;], x[,&quot;x2&quot;], col=&quot;black&quot;, xlab=&quot;x&quot;, ylab=&quot;y&quot;, main=&quot;normal values&quot;)
points(x[,&quot;x3&quot;], x[,&quot;x4&quot;], col=&quot;red&quot;)
legend(0, 0, &quot;scatters&quot;, fill=&quot;blue&quot;)</code></pre>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-24-4.png" width="672" /></p>
<pre class="r"><code>plot(x[,&quot;x1&quot;], x[,&quot;x2&quot;], col=&quot;black&quot;, xlab=&quot;x&quot;, ylab=&quot;y&quot;, main=&quot;normal values&quot;)
lines(sort(x[,&quot;x3&quot;], decreasing=T), sort(x[,&quot;x4&quot;], decreasing=T), col=&quot;blue&quot;,type=&quot;o&quot;)
text(0, 0, labels=&quot;* the position of (0,0)&quot;)

l &lt;- lm(sort(x[,&quot;x3&quot;], decreasing=T)~sort(x[,&quot;x4&quot;], decreasing=T))
abline(l$coefficients)
abline(h=0,col=&quot;red&quot;)
abline(v=0,col=&quot;green&quot;)</code></pre>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-24-5.png" width="672" /></p>
</div>
<div id="第三题-2" class="section level2">
<h2>第三题</h2>
<p>将屏幕分为四块并分别画出</p>
<pre class="r"><code>y=sin(x)
z=3*cos(x)
a=sin(x)*cos(x)
b=sin(x)/x
par(mfrow=c(2,2))
x &lt;- ((0:1000)/1000)*4*pi
plot(x, sin(x), col=&quot;red&quot;)
plot(x, 3*cos(x), col=&quot;blue&quot;)
plot(x, sin(x)*cos(x), col=&quot;yellow&quot;)
plot(x, sin(x)/x, col=&quot;green&quot;)</code></pre>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-25-1.png" width="672" /></p>
</div>
</div>
<div id="第六次作业" class="section level1">
<h1>第六次作业</h1>
</div>
<div id="第六次作业-1" class="section level1">
<h1>第六次作业</h1>
<div id="公司雇员数据分析" class="section level2">
<h2>公司雇员数据分析</h2>
<p>本次作业搜集到了公司的雇员数据，通过对数据进行统计分析，通过探索性分析得到相关结果。</p>
</div>
<div id="数据展示" class="section level2">
<h2>数据展示</h2>
<p>首先对读入的数据进行大致分析。</p>
<pre class="r"><code>library(tidyverse)</code></pre>
<pre><code>## -- Attaching packages --------------------------------------- tidyverse 1.3.1 --</code></pre>
<pre><code>## v tibble  3.1.2     v dplyr   1.0.6
## v tidyr   1.1.3     v stringr 1.4.0
## v readr   1.4.0     v forcats 0.5.1
## v purrr   0.3.4</code></pre>
<pre><code>## -- Conflicts ------------------------------------------ tidyverse_conflicts() --
## x dplyr::filter() masks stats::filter()
## x dplyr::lag()    masks stats::lag()</code></pre>
<pre class="r"><code>data&lt;-read.csv(&quot;Employee.csv&quot;,header = T)
rmarkdown::paged_table(data)</code></pre>
<div data-pagedtable="false">
<script data-pagedtable-source type="application/json">
{"columns":[{"label":["锘縤d"],"name":[1],"type":["int"],"align":["right"]},{"label":["gender"],"name":[2],"type":["chr"],"align":["left"]},{"label":["bdate"],"name":[3],"type":["chr"],"align":["left"]},{"label":["educ"],"name":[4],"type":["int"],"align":["right"]},{"label":["jobcat"],"name":[5],"type":["int"],"align":["right"]},{"label":["salary"],"name":[6],"type":["int"],"align":["right"]},{"label":["salbegin"],"name":[7],"type":["int"],"align":["right"]},{"label":["jobtime"],"name":[8],"type":["int"],"align":["right"]},{"label":["prevexp"],"name":[9],"type":["int"],"align":["right"]},{"label":["minority"],"name":[10],"type":["int"],"align":["right"]}],"data":[{"1":"1","2":"m","3":"2/3/52","4":"15","5":"3","6":"57000","7":"27000","8":"98","9":"144","10":"0"},{"1":"2","2":"m","3":"5/23/58","4":"16","5":"1","6":"40200","7":"18750","8":"98","9":"36","10":"0"},{"1":"3","2":"f","3":"7/26/29","4":"12","5":"1","6":"21450","7":"12000","8":"98","9":"381","10":"0"},{"1":"4","2":"f","3":"4/15/47","4":"8","5":"1","6":"21900","7":"13200","8":"98","9":"190","10":"0"},{"1":"5","2":"m","3":"2/9/55","4":"15","5":"1","6":"45000","7":"21000","8":"98","9":"138","10":"0"},{"1":"6","2":"m","3":"8/22/58","4":"15","5":"1","6":"32100","7":"13500","8":"98","9":"67","10":"0"},{"1":"7","2":"m","3":"4/26/56","4":"15","5":"1","6":"36000","7":"18750","8":"98","9":"114","10":"0"},{"1":"8","2":"f","3":"5/6/66","4":"12","5":"1","6":"21900","7":"9750","8":"98","9":"0","10":"0"},{"1":"9","2":"f","3":"1/23/46","4":"15","5":"1","6":"27900","7":"12750","8":"98","9":"115","10":"0"},{"1":"10","2":"f","3":"2/13/46","4":"12","5":"1","6":"24000","7":"13500","8":"98","9":"244","10":"0"},{"1":"11","2":"f","3":"2/7/50","4":"16","5":"1","6":"30300","7":"16500","8":"98","9":"143","10":"0"},{"1":"12","2":"m","3":"1/11/66","4":"8","5":"1","6":"28350","7":"12000","8":"98","9":"26","10":"1"},{"1":"13","2":"m","3":"7/17/60","4":"15","5":"1","6":"27750","7":"14250","8":"98","9":"34","10":"1"},{"1":"14","2":"f","3":"2/26/49","4":"15","5":"1","6":"35100","7":"16800","8":"98","9":"137","10":"1"},{"1":"15","2":"m","3":"8/29/62","4":"12","5":"1","6":"27300","7":"13500","8":"97","9":"66","10":"0"},{"1":"16","2":"m","3":"11/17/64","4":"12","5":"1","6":"40800","7":"15000","8":"97","9":"24","10":"0"},{"1":"17","2":"m","3":"7/18/62","4":"15","5":"1","6":"46000","7":"14250","8":"97","9":"48","10":"0"},{"1":"18","2":"m","3":"3/20/56","4":"16","5":"3","6":"103750","7":"27510","8":"97","9":"70","10":"0"},{"1":"19","2":"m","3":"8/19/62","4":"12","5":"1","6":"42300","7":"14250","8":"97","9":"103","10":"0"},{"1":"20","2":"f","3":"1/23/40","4":"12","5":"1","6":"26250","7":"11550","8":"97","9":"48","10":"0"},{"1":"21","2":"f","3":"2/19/63","4":"16","5":"1","6":"38850","7":"15000","8":"97","9":"17","10":"0"},{"1":"22","2":"m","3":"9/24/40","4":"12","5":"1","6":"21750","7":"12750","8":"97","9":"315","10":"1"},{"1":"23","2":"f","3":"3/15/65","4":"15","5":"1","6":"24000","7":"11100","8":"97","9":"75","10":"1"},{"1":"24","2":"f","3":"3/27/33","4":"12","5":"1","6":"16950","7":"9000","8":"97","9":"124","10":"1"},{"1":"25","2":"f","3":"7/1/42","4":"15","5":"1","6":"21150","7":"9000","8":"97","9":"171","10":"1"},{"1":"26","2":"m","3":"11/8/66","4":"15","5":"1","6":"31050","7":"12600","8":"96","9":"14","10":"0"},{"1":"27","2":"m","3":"3/19/54","4":"19","5":"3","6":"60375","7":"27480","8":"96","9":"96","10":"0"},{"1":"28","2":"m","3":"4/11/63","4":"15","5":"1","6":"32550","7":"14250","8":"96","9":"43","10":"0"},{"1":"29","2":"m","3":"1/28/44","4":"19","5":"3","6":"135000","7":"79980","8":"96","9":"199","10":"0"},{"1":"30","2":"m","3":"9/17/61","4":"15","5":"1","6":"31200","7":"14250","8":"96","9":"54","10":"0"},{"1":"31","2":"m","3":"2/24/64","4":"12","5":"1","6":"36150","7":"14250","8":"96","9":"83","10":"0"},{"1":"32","2":"m","3":"1/28/54","4":"19","5":"3","6":"110625","7":"45000","8":"96","9":"120","10":"0"},{"1":"33","2":"m","3":"3/18/61","4":"15","5":"1","6":"42000","7":"15000","8":"96","9":"68","10":"0"},{"1":"34","2":"m","3":"2/2/49","4":"19","5":"3","6":"92000","7":"39990","8":"96","9":"175","10":"0"},{"1":"35","2":"m","3":"8/22/61","4":"17","5":"3","6":"81250","7":"30000","8":"96","9":"18","10":"0"},{"1":"36","2":"f","3":"8/7/63","4":"8","5":"1","6":"31350","7":"11250","8":"96","9":"52","10":"0"},{"1":"37","2":"m","3":"10/9/54","4":"12","5":"1","6":"29100","7":"13500","8":"96","9":"113","10":"1"},{"1":"38","2":"m","3":"4/27/62","4":"15","5":"1","6":"31350","7":"15000","8":"96","9":"49","10":"1"},{"1":"39","2":"m","3":"6/22/60","4":"16","5":"1","6":"36000","7":"15000","8":"96","9":"46","10":"1"},{"1":"40","2":"f","3":"8/28/33","4":"15","5":"1","6":"19200","7":"9000","8":"96","9":"23","10":"1"},{"1":"41","2":"f","3":"3/18/61","4":"12","5":"1","6":"23550","7":"11550","8":"96","9":"52","10":"1"},{"1":"42","2":"m","3":"9/23/60","4":"15","5":"1","6":"35100","7":"16500","8":"95","9":"90","10":"0"},{"1":"43","2":"m","3":"1/18/64","4":"12","5":"1","6":"23250","7":"14250","8":"95","9":"46","10":"0"},{"1":"44","2":"m","3":"6/15/63","4":"8","5":"1","6":"29250","7":"14250","8":"95","9":"50","10":"0"},{"1":"45","2":"m","3":"8/2/38","4":"12","5":"2","6":"30750","7":"13500","8":"95","9":"307","10":"0"},{"1":"46","2":"f","3":"11/18/40","4":"15","5":"1","6":"22350","7":"12750","8":"95","9":"165","10":"0"},{"1":"47","2":"f","3":"4/28/38","4":"12","5":"1","6":"30000","7":"16500","8":"95","9":"228","10":"0"},{"1":"48","2":"m","3":"6/7/47","4":"12","5":"2","6":"30750","7":"14100","8":"94","9":"240","10":"0"},{"1":"49","2":"m","3":"9/16/58","4":"15","5":"1","6":"34800","7":"16500","8":"94","9":"93","10":"0"},{"1":"50","2":"m","3":"2/9/60","4":"16","5":"3","6":"60000","7":"23730","8":"94","9":"59","10":"0"},{"1":"51","2":"m","3":"7/8/62","4":"12","5":"1","6":"35550","7":"15000","8":"94","9":"48","10":"0"},{"1":"52","2":"m","3":"11/12/63","4":"15","5":"1","6":"45150","7":"15000","8":"94","9":"40","10":"0"},{"1":"53","2":"m","3":"4/21/54","4":"18","5":"3","6":"73750","7":"26250","8":"94","9":"56","10":"0"},{"1":"54","2":"m","3":"6/4/31","4":"12","5":"1","6":"25050","7":"13500","8":"94","9":"444","10":"0"},{"1":"55","2":"m","3":"6/25/60","4":"12","5":"1","6":"27000","7":"15000","8":"94","9":"120","10":"0"},{"1":"56","2":"m","3":"4/16/62","4":"15","5":"1","6":"26850","7":"13500","8":"94","9":"5","10":"0"},{"1":"57","2":"m","3":"4/15/63","4":"15","5":"1","6":"33900","7":"15750","8":"94","9":"78","10":"0"},{"1":"58","2":"f","3":"11/14/64","4":"15","5":"1","6":"26400","7":"13500","8":"94","9":"3","10":"0"},{"1":"59","2":"m","3":"5/7/61","4":"15","5":"1","6":"28050","7":"14250","8":"94","9":"36","10":"1"},{"1":"60","2":"m","3":"2/16/59","4":"12","5":"1","6":"30900","7":"15000","8":"94","9":"102","10":"1"},{"1":"61","2":"m","3":"4/28/64","4":"8","5":"1","6":"22500","7":"9750","8":"94","9":"36","10":"1"},{"1":"62","2":"m","3":"7/18/62","4":"16","5":"3","6":"48000","7":"21750","8":"93","9":"22","10":"0"},{"1":"63","2":"m","3":"8/20/61","4":"17","5":"3","6":"55000","7":"26250","8":"93","9":"32","10":"0"},{"1":"64","2":"m","3":"9/28/63","4":"16","5":"3","6":"53125","7":"21000","8":"93","9":"48","10":"0"},{"1":"65","2":"m","3":"3/28/64","4":"8","5":"1","6":"21900","7":"14550","8":"93","9":"41","10":"0"},{"1":"66","2":"m","3":"2/16/62","4":"19","5":"3","6":"78125","7":"30000","8":"93","9":"7","10":"0"},{"1":"67","2":"m","3":"5/28/64","4":"16","5":"3","6":"46000","7":"21240","8":"93","9":"35","10":"0"},{"1":"68","2":"m","3":"5/5/63","4":"16","5":"3","6":"45250","7":"21480","8":"93","9":"36","10":"0"},{"1":"69","2":"m","3":"6/23/60","4":"16","5":"3","6":"56550","7":"25000","8":"93","9":"34","10":"0"},{"1":"70","2":"m","3":"2/8/62","4":"15","5":"1","6":"41100","7":"20250","8":"93","9":"27","10":"0"},{"1":"71","2":"m","3":"8/26/48","4":"17","5":"3","6":"82500","7":"34980","8":"93","9":"207","10":"0"},{"1":"72","2":"f","3":"1/7/64","4":"16","5":"1","6":"54000","7":"18000","8":"93","9":"11","10":"0"},{"1":"73","2":"f","3":"2/9/68","4":"12","5":"1","6":"26400","7":"10500","8":"93","9":"0","10":"0"},{"1":"74","2":"f","3":"4/28/33","4":"15","5":"1","6":"33900","7":"19500","8":"93","9":"192","10":"0"},{"1":"75","2":"f","3":"8/12/65","4":"15","5":"1","6":"24150","7":"11550","8":"93","9":"0","10":"0"},{"1":"76","2":"f","3":"9/3/67","4":"15","5":"1","6":"29250","7":"11550","8":"93","9":"11","10":"0"},{"1":"77","2":"f","3":"9/9/68","4":"12","5":"1","6":"27600","7":"11400","8":"93","9":"6","10":"0"},{"1":"78","2":"f","3":"8/20/68","4":"12","5":"1","6":"22950","7":"10500","8":"93","9":"10","10":"0"},{"1":"79","2":"f","3":"1/23/62","4":"16","5":"1","6":"34800","7":"14550","8":"93","9":"8","10":"0"},{"1":"80","2":"f","3":"5/25/61","4":"16","5":"1","6":"51000","7":"18000","8":"93","9":"22","10":"0"},{"1":"81","2":"f","3":"3/12/68","4":"12","5":"1","6":"24300","7":"10950","8":"93","9":"5","10":"0"},{"1":"82","2":"f","3":"8/28/47","4":"12","5":"1","6":"24750","7":"14250","8":"93","9":"193","10":"1"},{"1":"83","2":"f","3":"10/12/67","4":"12","5":"1","6":"22950","7":"11250","8":"93","9":"0","10":"1"},{"1":"84","2":"f","3":"3/12/67","4":"8","5":"1","6":"25050","7":"10950","8":"93","9":"8","10":"1"},{"1":"85","2":"m","3":"4/9/62","4":"15","5":"1","6":"25950","7":"17100","8":"92","9":"42","10":"0"},{"1":"86","2":"m","3":"8/25/61","4":"15","5":"1","6":"31650","7":"15750","8":"92","9":"64","10":"0"},{"1":"87","2":"m","3":"10/20/59","4":"12","5":"1","6":"24150","7":"14100","8":"92","9":"130","10":"0"},{"1":"88","2":"m","3":"2/10/62","4":"19","5":"3","6":"72500","7":"28740","8":"92","9":"10","10":"0"},{"1":"89","2":"m","3":"6/24/61","4":"19","5":"3","6":"68750","7":"27480","8":"92","9":"8","10":"0"},{"1":"90","2":"f","3":"2/27/38","4":"8","5":"1","6":"16200","7":"9750","8":"92","9":"0","10":"0"},{"1":"91","2":"f","3":"11/4/67","4":"12","5":"1","6":"20100","7":"11250","8":"92","9":"24","10":"0"},{"1":"92","2":"f","3":"6/25/68","4":"8","5":"1","6":"24000","7":"10950","8":"92","9":"6","10":"0"},{"1":"93","2":"f","3":"3/5/68","4":"12","5":"1","6":"25950","7":"10950","8":"92","9":"0","10":"0"},{"1":"94","2":"f","3":"8/4/50","4":"12","5":"1","6":"24600","7":"10050","8":"92","9":"44","10":"0"},{"1":"95","2":"f","3":"8/8/68","4":"12","5":"1","6":"28500","7":"10500","8":"92","9":"6","10":"0"},{"1":"96","2":"m","3":"10/2/33","4":"8","5":"2","6":"30750","7":"15000","8":"92","9":"432","10":"1"},{"1":"97","2":"m","3":"1/18/53","4":"17","5":"1","6":"40200","7":"19500","8":"92","9":"168","10":"1"},{"1":"98","2":"m","3":"5/17/56","4":"8","5":"2","6":"30000","7":"15000","8":"92","9":"144","10":"1"},{"1":"99","2":"f","3":"7/7/68","4":"12","5":"1","6":"22050","7":"10950","8":"92","9":"5","10":"1"},{"1":"100","2":"m","3":"10/25/63","4":"18","5":"3","6":"78250","7":"27480","8":"91","9":"47","10":"0"},{"1":"101","2":"m","3":"3/14/60","4":"16","5":"3","6":"60625","7":"22500","8":"91","9":"44","10":"0"},{"1":"102","2":"m","3":"3/28/63","4":"14","5":"1","6":"39900","7":"15750","8":"91","9":"59","10":"0"},{"1":"103","2":"m","3":"3/17/59","4":"19","5":"3","6":"97000","7":"35010","8":"91","9":"68","10":"0"},{"1":"104","2":"m","3":"11/5/62","4":"15","5":"1","6":"27450","7":"15750","8":"91","9":"48","10":"0"},{"1":"105","2":"m","3":"3/7/66","4":"15","5":"1","6":"31650","7":"13500","8":"91","9":"18","10":"0"},{"1":"106","2":"m","3":"8/4/62","4":"19","5":"3","6":"91250","7":"29490","8":"91","9":"23","10":"0"},{"1":"107","2":"f","3":"8/16/60","4":"12","5":"1","6":"25200","7":"14400","8":"91","9":"83","10":"0"},{"1":"108","2":"f","3":"7/16/30","4":"12","5":"1","6":"21000","7":"11550","8":"91","9":"108","10":"0"},{"1":"109","2":"m","3":"11/10/63","4":"12","5":"1","6":"30450","7":"15000","8":"91","9":"49","10":"1"},{"1":"110","2":"m","3":"10/29/52","4":"15","5":"1","6":"28350","7":"18000","8":"91","9":"151","10":"1"},{"1":"111","2":"m","3":"11/27/40","4":"12","5":"2","6":"30750","7":"9000","8":"91","9":"314","10":"1"},{"1":"112","2":"m","3":"6/21/48","4":"12","5":"2","6":"30750","7":"15000","8":"91","9":"240","10":"1"},{"1":"113","2":"m","3":"10/6/59","4":"16","5":"3","6":"54875","7":"27480","8":"90","9":"68","10":"0"},{"1":"114","2":"m","3":"8/25/61","4":"14","5":"1","6":"37800","7":"16500","8":"90","9":"60","10":"0"},{"1":"115","2":"m","3":"5/12/61","4":"15","5":"1","6":"33450","7":"14100","8":"90","9":"85","10":"0"},{"1":"116","2":"m","3":"6/9/62","4":"15","5":"1","6":"30300","7":"16500","8":"90","9":"16","10":"0"},{"1":"117","2":"f","3":"1/14/32","4":"12","5":"1","6":"31500","7":"18750","8":"90","9":"205","10":"0"},{"1":"118","2":"f","3":"3/4/64","4":"12","5":"1","6":"31650","7":"14250","8":"90","9":"48","10":"0"},{"1":"119","2":"f","3":"7/23/63","4":"12","5":"1","6":"25200","7":"14100","8":"90","9":"55","10":"0"},{"1":"120","2":"f","3":"11/12/64","4":"16","5":"3","6":"37800","7":"15750","8":"90","9":"7","10":"0"},{"1":"121","2":"f","3":"8/6/36","4":"15","5":"1","6":"18750","7":"10500","8":"90","9":"54","10":"0"},{"1":"122","2":"f","3":"9/26/65","4":"15","5":"1","6":"32550","7":"13500","8":"90","9":"22","10":"0"},{"1":"123","2":"f","3":"4/24/49","4":"12","5":"1","6":"33300","7":"15000","8":"90","9":"3","10":"0"},{"1":"124","2":"f","3":"5/29/63","4":"16","5":"1","6":"38550","7":"16500","8":"90","9":"0","10":"0"},{"1":"125","2":"m","3":"8/6/56","4":"12","5":"1","6":"27450","7":"15000","8":"90","9":"173","10":"1"},{"1":"126","2":"m","3":"1/21/51","4":"15","5":"2","6":"24300","7":"15000","8":"90","9":"191","10":"1"},{"1":"127","2":"m","3":"9/1/50","4":"12","5":"2","6":"30750","7":"15000","8":"90","9":"209","10":"1"},{"1":"128","2":"f","3":"7/25/46","4":"12","5":"1","6":"19650","7":"9750","8":"90","9":"229","10":"1"},{"1":"129","2":"m","3":"7/18/59","4":"17","5":"3","6":"68750","7":"27510","8":"89","9":"38","10":"0"},{"1":"130","2":"m","3":"9/6/58","4":"20","5":"3","6":"59375","7":"30000","8":"89","9":"6","10":"0"},{"1":"131","2":"m","3":"2/8/62","4":"15","5":"1","6":"31500","7":"15750","8":"89","9":"22","10":"0"},{"1":"132","2":"m","3":"5/17/53","4":"12","5":"1","6":"27300","7":"17250","8":"89","9":"175","10":"0"},{"1":"133","2":"m","3":"9/12/59","4":"15","5":"1","6":"27000","7":"15750","8":"89","9":"87","10":"0"},{"1":"134","2":"f","3":"11/10/41","4":"16","5":"3","6":"41550","7":"24990","8":"89","9":"285","10":"0"},{"1":"135","2":"f","3":"5/22/68","4":"12","5":"1","6":"26250","7":"10950","8":"89","9":"0","10":"0"},{"1":"136","2":"m","3":"8/25/39","4":"12","5":"1","6":"22200","7":"15000","8":"88","9":"324","10":"0"},{"1":"137","2":"m","3":"7/12/37","4":"21","5":"3","6":"65000","7":"37500","8":"88","9":"264","10":"0"},{"1":"138","2":"m","3":"1/9/47","4":"12","5":"1","6":"30900","7":"15000","8":"88","9":"252","10":"0"},{"1":"139","2":"f","3":"6/18/31","4":"8","5":"1","6":"20100","7":"13200","8":"88","9":"90","10":"0"},{"1":"140","2":"f","3":"4/5/65","4":"12","5":"1","6":"22350","7":"13500","8":"88","9":"26","10":"0"},{"1":"141","2":"f","3":"6/14/66","4":"15","5":"1","6":"35550","7":"13350","8":"88","9":"32","10":"0"},{"1":"142","2":"f","3":"11/13/66","4":"12","5":"1","6":"28500","7":"13950","8":"88","9":"34","10":"0"},{"1":"143","2":"f","3":"8/24/39","4":"12","5":"1","6":"24450","7":"13200","8":"88","9":"107","10":"0"},{"1":"144","2":"f","3":"8/28/31","4":"8","5":"1","6":"16650","7":"9750","8":"88","9":"412","10":"0"},{"1":"145","2":"m","3":"1/15/64","4":"12","5":"1","6":"26700","7":"13500","8":"88","9":"38","10":"1"},{"1":"146","2":"m","3":"1/2/51","4":"18","5":"1","6":"43950","7":"23250","8":"88","9":"182","10":"1"},{"1":"147","2":"m","3":"9/11/36","4":"15","5":"1","6":"23700","7":"13500","8":"88","9":"359","10":"1"},{"1":"148","2":"f","3":"10/5/59","4":"15","5":"1","6":"26550","7":"14250","8":"88","9":"61","10":"1"},{"1":"149","2":"m","3":"6/28/62","4":"12","5":"1","6":"27600","7":"15000","8":"87","9":"75","10":"0"},{"1":"150","2":"m","3":"3/5/54","4":"12","5":"1","6":"25800","7":"15000","8":"87","9":"143","10":"0"},{"1":"151","2":"m","3":"8/16/54","4":"16","5":"3","6":"42300","7":"26250","8":"87","9":"126","10":"0"},{"1":"152","2":"m","3":"2005/3/29","4":"8","5":"2","6":"30750","7":"15000","8":"87","9":"451","10":"0"},{"1":"153","2":"f","3":"5/13/67","4":"12","5":"1","6":"26700","7":"12900","8":"87","9":"18","10":"0"},{"1":"154","2":"f","3":"6/7/40","4":"12","5":"1","6":"20850","7":"12000","8":"87","9":"163","10":"0"},{"1":"155","2":"m","3":"3/6/63","4":"15","5":"1","6":"35250","7":"15000","8":"87","9":"54","10":"1"},{"1":"156","2":"m","3":"1/12/63","4":"15","5":"1","6":"26700","7":"15000","8":"87","9":"56","10":"1"},{"1":"157","2":"f","3":"7/2/67","4":"12","5":"1","6":"26550","7":"13050","8":"87","9":"11","10":"1"},{"1":"158","2":"f","3":"9/20/64","4":"12","5":"1","6":"27750","7":"12000","8":"87","9":"11","10":"1"},{"1":"159","2":"f","3":"1/13/51","4":"16","5":"1","6":"25050","7":"12750","8":"87","9":"123","10":"1"},{"1":"160","2":"m","3":"8/27/51","4":"16","5":"3","6":"66000","7":"47490","8":"86","9":"150","10":"0"},{"1":"161","2":"m","3":"2/11/63","4":"16","5":"1","6":"52650","7":"19500","8":"86","9":"20","10":"0"},{"1":"162","2":"m","3":"5/25/61","4":"16","5":"3","6":"45625","7":"23250","8":"86","9":"60","10":"0"},{"1":"163","2":"m","3":"11/10/65","4":"15","5":"1","6":"30900","7":"15000","8":"86","9":"25","10":"0"},{"1":"164","2":"f","3":"8/13/65","4":"15","5":"1","6":"29400","7":"16500","8":"86","9":"24","10":"0"},{"1":"165","2":"f","3":"4/29/66","4":"15","5":"1","6":"33300","7":"13500","8":"86","9":"24","10":"0"},{"1":"166","2":"f","3":"7/12/42","4":"12","5":"1","6":"21900","7":"9750","8":"86","9":"156","10":"0"},{"1":"167","2":"f","3":"8/26/32","4":"12","5":"1","6":"18150","7":"9750","8":"86","9":"72","10":"0"},{"1":"168","2":"f","3":"4/23/62","4":"16","5":"3","6":"46875","7":"17250","8":"86","9":"19","10":"0"},{"1":"169","2":"m","3":"5/23/65","4":"12","5":"1","6":"25500","7":"14400","8":"86","9":"37","10":"1"},{"1":"170","2":"m","3":"6/13/64","4":"12","5":"1","6":"26550","7":"15000","8":"86","9":"38","10":"1"},{"1":"171","2":"m","3":"1/21/30","4":"12","5":"1","6":"26700","7":"13500","8":"86","9":"367","10":"1"},{"1":"172","2":"f","3":"6/13/53","4":"15","5":"1","6":"29850","7":"15000","8":"86","9":"79","10":"1"},{"1":"173","2":"m","3":"1/15/50","4":"20","5":"3","6":"69250","7":"42480","8":"85","9":"134","10":"0"},{"1":"174","2":"m","3":"1/7/35","4":"8","5":"2","6":"31950","7":"15000","8":"85","9":"438","10":"0"},{"1":"175","2":"m","3":"1/8/38","4":"8","5":"1","6":"26250","7":"15600","8":"85","9":"171","10":"0"},{"1":"176","2":"f","3":"10/5/62","4":"16","5":"1","6":"35700","7":"17250","8":"85","9":"19","10":"0"},{"1":"177","2":"f","3":"8/11/62","4":"12","5":"1","6":"28500","7":"16500","8":"85","9":"69","10":"0"},{"1":"178","2":"f","3":"1/17/38","4":"12","5":"1","6":"17100","7":"10200","8":"85","9":"72","10":"0"},{"1":"179","2":"m","3":"1/19/65","4":"12","5":"1","6":"25200","7":"13050","8":"85","9":"29","10":"1"},{"1":"180","2":"f","3":"1/23/60","4":"12","5":"1","6":"24000","7":"12750","8":"85","9":"59","10":"1"},{"1":"181","2":"f","3":"1/4/39","4":"12","5":"1","6":"27450","7":"10200","8":"85","9":"101","10":"1"},{"1":"182","2":"f","3":"3/8/43","4":"12","5":"1","6":"18450","7":"10200","8":"85","9":"228","10":"1"},{"1":"183","2":"m","3":"3/1/60","4":"15","5":"1","6":"39300","7":"15750","8":"84","9":"72","10":"0"},{"1":"184","2":"m","3":"11/5/64","4":"15","5":"1","6":"38850","7":"15000","8":"84","9":"53","10":"0"},{"1":"185","2":"m","3":"8/28/30","4":"8","5":"2","6":"30750","7":"15000","8":"84","9":"380","10":"0"},{"1":"186","2":"m","3":"7/6/64","4":"15","5":"1","6":"37500","7":"20400","8":"84","9":"33","10":"0"},{"1":"187","2":"m","3":"7/29/63","4":"16","5":"3","6":"58750","7":"21750","8":"84","9":"13","10":"0"},{"1":"188","2":"f","3":"2/4/34","4":"12","5":"1","6":"34500","7":"18750","8":"84","9":"208","10":"0"},{"1":"189","2":"f","3":"3/28/50","4":"12","5":"1","6":"36000","7":"19980","8":"84","9":"240","10":"0"},{"1":"190","2":"f","3":"11/15/32","4":"8","5":"1","6":"29100","7":"16500","8":"84","9":"35","10":"0"},{"1":"191","2":"f","3":"10/23/31","4":"12","5":"1","6":"16500","7":"10200","8":"84","9":"288","10":"0"},{"1":"192","2":"m","3":"10/9/49","4":"12","5":"1","6":"19650","7":"12750","8":"84","9":"180","10":"1"},{"1":"193","2":"f","3":"7/22/66","4":"12","5":"1","6":"24750","7":"12000","8":"84","9":"41","10":"1"},{"1":"194","2":"f","3":"4/10/38","4":"15","5":"1","6":"27150","7":"15750","8":"84","9":"231","10":"1"},{"1":"195","2":"f","3":"11/6/55","4":"12","5":"1","6":"26400","7":"12750","8":"84","9":"36","10":"1"},{"1":"196","2":"f","3":"3/3/46","4":"16","5":"1","6":"23100","7":"12000","8":"84","9":"214","10":"1"},{"1":"197","2":"m","3":"10/1/62","4":"15","5":"3","6":"54900","7":"25500","8":"83","9":"49","10":"0"},{"1":"198","2":"m","3":"3/17/52","4":"19","5":"3","6":"70875","7":"43500","8":"83","9":"156","10":"0"},{"1":"199","2":"m","3":"2/2/58","4":"16","5":"3","6":"51250","7":"27480","8":"83","9":"69","10":"0"},{"1":"200","2":"m","3":"2/13/63","4":"17","5":"3","6":"67500","7":"34980","8":"83","9":"9","10":"0"},{"1":"201","2":"m","3":"5/8/55","4":"12","5":"1","6":"29340","7":"19500","8":"83","9":"150","10":"0"},{"1":"202","2":"m","3":"3/17/63","4":"15","5":"1","6":"39600","7":"16500","8":"83","9":"47","10":"0"},{"1":"203","2":"m","3":"3/17/64","4":"12","5":"1","6":"29100","7":"15000","8":"83","9":"50","10":"0"},{"1":"204","2":"m","3":"10/21/60","4":"15","5":"1","6":"33150","7":"16500","8":"83","9":"69","10":"0"},{"1":"205","2":"m","3":"6/22/44","4":"16","5":"3","6":"66750","7":"52500","8":"83","9":"258","10":"0"},{"1":"206","2":"m","3":"5/22/43","4":"12","5":"2","6":"33750","7":"15000","8":"83","9":"284","10":"0"},{"1":"207","2":"m","3":"2/15/59","4":"15","5":"1","6":"27300","7":"17250","8":"83","9":"91","10":"0"},{"1":"208","2":"f","3":"11/28/68","4":"12","5":"1","6":"24000","7":"11250","8":"83","9":"16","10":"0"},{"1":"209","2":"f","3":"1/14/34","4":"8","5":"1","6":"19800","7":"10200","8":"83","9":"75","10":"0"},{"1":"210","2":"m","3":"5/4/49","4":"15","5":"1","6":"30600","7":"16500","8":"83","9":"216","10":"1"},{"1":"211","2":"m","3":"11/8/50","4":"15","5":"1","6":"28950","7":"15000","8":"83","9":"108","10":"1"},{"1":"212","2":"m","3":"5/14/65","4":"15","5":"1","6":"38400","7":"16500","8":"83","9":"64","10":"1"},{"1":"213","2":"m","3":"10/20/45","4":"8","5":"2","6":"30750","7":"15000","8":"83","9":"302","10":"1"},{"1":"214","2":"f","3":"9/13/68","4":"12","5":"1","6":"20400","7":"10950","8":"83","9":"9","10":"1"},{"1":"215","2":"f","3":"9/15/68","4":"12","5":"1","6":"19200","7":"11100","8":"83","9":"7","10":"1"},{"1":"216","2":"m","3":"5/16/64","4":"15","5":"1","6":"30150","7":"15750","8":"82","9":"72","10":"0"},{"1":"217","2":"m","3":"3/15/49","4":"16","5":"1","6":"34620","7":"27750","8":"82","9":"149","10":"0"},{"1":"218","2":"m","3":"3/21/64","4":"15","5":"1","6":"80000","7":"15750","8":"82","9":"34","10":"0"},{"1":"219","2":"m","3":"2/2/63","4":"12","5":"1","6":"25350","7":"15000","8":"82","9":"32","10":"0"},{"1":"220","2":"m","3":"8/17/63","4":"12","5":"1","6":"29850","7":"15750","8":"82","9":"85","10":"0"},{"1":"221","2":"f","3":"5/22/47","4":"12","5":"1","6":"24000","7":"13800","8":"82","9":"97","10":"0"},{"1":"222","2":"f","3":"9/15/35","4":"15","5":"1","6":"27750","7":"19500","8":"82","9":"265","10":"0"},{"1":"223","2":"f","3":"3/14/42","4":"8","5":"1","6":"22350","7":"10200","8":"82","9":"48","10":"0"},{"1":"224","2":"f","3":"11/20/34","4":"12","5":"1","6":"16200","7":"10200","8":"82","9":"0","10":"0"},{"1":"225","2":"f","3":"10/13/67","4":"15","5":"1","6":"21900","7":"12750","8":"82","9":"0","10":"0"},{"1":"226","2":"f","3":"6/21/64","4":"16","5":"1","6":"23250","7":"15750","8":"82","9":"4","10":"0"},{"1":"227","2":"f","3":"7/17/65","4":"12","5":"1","6":"33900","7":"12000","8":"82","9":"11","10":"0"},{"1":"228","2":"f","3":"9/21/63","4":"15","5":"1","6":"25650","7":"14250","8":"82","9":"51","10":"0"},{"1":"229","2":"f","3":"8/21/40","4":"12","5":"1","6":"17250","7":"10200","8":"82","9":"358","10":"0"},{"1":"230","2":"m","3":"2/4/34","4":"15","5":"1","6":"22500","7":"15000","8":"82","9":"371","10":"1"},{"1":"231","2":"m","3":"1/9/65","4":"16","5":"3","6":"40200","7":"21000","8":"81","9":"3","10":"0"},{"1":"232","2":"m","3":"9/13/63","4":"19","5":"3","6":"55500","7":"33750","8":"81","9":"62","10":"0"},{"1":"233","2":"m","3":"7/21/63","4":"15","5":"1","6":"26550","7":"15000","8":"81","9":"52","10":"0"},{"1":"234","2":"m","3":"11/12/60","4":"15","5":"1","6":"50550","7":"19500","8":"81","9":"44","10":"0"},{"1":"235","2":"m","3":"9/11/62","4":"19","5":"3","6":"75000","7":"31500","8":"81","9":"13","10":"0"},{"1":"236","2":"f","3":"5/2/69","4":"8","5":"1","6":"27450","7":"12000","8":"81","9":"9","10":"0"},{"1":"237","2":"f","3":"6/4/69","4":"12","5":"1","6":"22650","7":"11250","8":"81","9":"0","10":"0"},{"1":"238","2":"f","3":"6/15/69","4":"12","5":"1","6":"27300","7":"11250","8":"81","9":"5","10":"0"},{"1":"239","2":"f","3":"9/14/69","4":"12","5":"1","6":"27750","7":"11225","8":"81","9":"5","10":"0"},{"1":"240","2":"f","3":"6/15/61","4":"16","5":"3","6":"54375","7":"18750","8":"81","9":"81","10":"0"},{"1":"241","2":"f","3":"8/27/36","4":"8","5":"1","6":"17400","7":"10200","8":"81","9":"390","10":"0"},{"1":"242","2":"f","3":"11/3/67","4":"12","5":"1","6":"40800","7":"18000","8":"81","9":"4","10":"0"},{"1":"243","2":"f","3":"2/10/69","4":"12","5":"1","6":"23100","7":"10950","8":"81","9":"0","10":"0"},{"1":"244","2":"f","3":"9/15/69","4":"8","5":"1","6":"22500","7":"10950","8":"81","9":"5","10":"0"},{"1":"245","2":"f","3":"3/16/69","4":"12","5":"1","6":"26700","7":"11550","8":"81","9":"18","10":"0"},{"1":"246","2":"f","3":"1/14/68","4":"12","5":"1","6":"24900","7":"11250","8":"81","9":"0","10":"0"},{"1":"247","2":"f","3":"5/13/68","4":"12","5":"1","6":"19650","7":"10950","8":"81","9":"11","10":"0"},{"1":"248","2":"f","3":"4/9/69","4":"12","5":"1","6":"22050","7":"10950","8":"81","9":"9","10":"0"},{"1":"249","2":"f","3":"5/9/69","4":"12","5":"1","6":"25500","7":"12000","8":"81","9":"11","10":"0"},{"1":"250","2":"f","3":"10/10/66","4":"15","5":"1","6":"28200","7":"12750","8":"81","9":"19","10":"0"},{"1":"251","2":"f","3":"1/19/69","4":"12","5":"1","6":"23100","7":"11250","8":"81","9":"13","10":"0"},{"1":"252","2":"m","3":"9/18/69","4":"12","5":"1","6":"25500","7":"11400","8":"81","9":"9","10":"1"},{"1":"253","2":"f","3":"2/21/42","4":"8","5":"1","6":"17100","7":"10200","8":"81","9":"0","10":"1"},{"1":"254","2":"m","3":"2/8/64","4":"18","5":"3","6":"68125","7":"32490","8":"80","9":"29","10":"0"},{"1":"255","2":"m","3":"8/15/32","4":"12","5":"2","6":"30600","7":"15750","8":"80","9":"460","10":"0"},{"1":"256","2":"m","3":"1/3/48","4":"19","5":"3","6":"52125","7":"27480","8":"80","9":"221","10":"0"},{"1":"257","2":"m","3":"9/24/51","4":"19","5":"3","6":"61875","7":"36750","8":"80","9":"199","10":"0"},{"1":"258","2":"m","3":"3/9/69","4":"8","5":"1","6":"21300","7":"11550","8":"80","9":"24","10":"0"},{"1":"259","2":"f","3":"3/15/69","4":"12","5":"1","6":"19650","7":"11250","8":"80","9":"5","10":"0"},{"1":"260","2":"f","3":"2/20/69","4":"12","5":"1","6":"22350","7":"11250","8":"80","9":"5","10":"0"},{"1":"261","2":"f","3":"3/27/69","4":"12","5":"1","6":"23400","7":"11250","8":"80","9":"18","10":"0"},{"1":"262","2":"f","3":"6/20/68","4":"12","5":"1","6":"24300","7":"10950","8":"80","9":"8","10":"0"},{"1":"263","2":"f","3":"10/13/68","4":"12","5":"1","6":"28500","7":"11250","8":"80","9":"4","10":"0"},{"1":"264","2":"f","3":"1/16/69","4":"12","5":"1","6":"19950","7":"11250","8":"80","9":"8","10":"0"},{"1":"265","2":"f","3":"9/24/69","4":"12","5":"1","6":"23400","7":"11250","8":"80","9":"0","10":"0"},{"1":"266","2":"f","3":"10/7/63","4":"16","5":"1","6":"34500","7":"17250","8":"80","9":"3","10":"0"},{"1":"267","2":"f","3":"8/24/69","4":"12","5":"1","6":"18150","7":"10950","8":"80","9":"0","10":"0"},{"1":"268","2":"m","3":"5/16/36","4":"12","5":"1","6":"22350","7":"15000","8":"80","9":"272","10":"1"},{"1":"269","2":"m","3":"3/17/66","4":"15","5":"1","6":"40200","7":"17250","8":"79","9":"38","10":"0"},{"1":"270","2":"m","3":"10/29/47","4":"15","5":"1","6":"28650","7":"18000","8":"79","9":"261","10":"0"},{"1":"271","2":"m","3":"8/24/63","4":"15","5":"1","6":"27750","7":"16500","8":"79","9":"55","10":"0"},{"1":"272","2":"m","3":"6/17/64","4":"18","5":"1","6":"66875","7":"31980","8":"79","9":"30","10":"0"},{"1":"273","2":"m","3":"11/12/39","4":"12","5":"2","6":"30000","7":"15750","8":"79","9":"308","10":"0"},{"1":"274","2":"m","3":"8/4/64","4":"16","5":"3","6":"83750","7":"21750","8":"79","9":"12","10":"0"},{"1":"275","2":"m","3":"1/14/63","4":"12","5":"1","6":"33900","7":"16500","8":"79","9":"94","10":"0"},{"1":"276","2":"m","3":"5/11/65","4":"16","5":"3","6":"56500","7":"21000","8":"79","9":"12","10":"0"},{"1":"277","2":"f","3":"5/20/65","4":"16","5":"3","6":"43000","7":"17490","8":"79","9":"20","10":"0"},{"1":"278","2":"f","3":"6/12/43","4":"8","5":"1","6":"20850","7":"12000","8":"79","9":"70","10":"0"},{"1":"279","2":"f","3":"4/16/69","4":"12","5":"1","6":"24450","7":"12000","8":"79","9":"8","10":"0"},{"1":"280","2":"f","3":"10/20/69","4":"12","5":"1","6":"24750","7":"10950","8":"79","9":"5","10":"0"},{"1":"281","2":"m","3":"2/18/45","4":"8","5":"2","6":"34500","7":"15750","8":"79","9":"246","10":"1"},{"1":"282","2":"m","3":"9/15/63","4":"14","5":"1","6":"27900","7":"15000","8":"79","9":"47","10":"1"},{"1":"283","2":"m","3":"2/25/63","4":"19","5":"3","6":"68125","7":"32010","8":"78","9":"35","10":"0"},{"1":"284","2":"m","3":"10/10/61","4":"19","5":"3","6":"73500","7":"33000","8":"78","9":"45","10":"0"},{"1":"285","2":"m","3":"5/28/30","4":"8","5":"2","6":"30750","7":"15750","8":"78","9":"429","10":"0"},{"1":"286","2":"m","3":"3/7/58","4":"15","5":"3","6":"40050","7":"25500","8":"78","9":"133","10":"0"},{"1":"287","2":"m","3":"1/18/65","4":"16","5":"1","6":"40350","7":"19500","8":"78","9":"20","10":"0"},{"1":"288","2":"m","3":"1/22/55","4":"15","5":"3","6":"38700","7":"23730","8":"78","9":"176","10":"0"},{"1":"289","2":"m","3":"10/27/64","4":"17","5":"3","6":"65000","7":"30750","8":"78","9":"26","10":"0"},{"1":"290","2":"m","3":"4/5/54","4":"18","5":"3","6":"51450","7":"36240","8":"78","9":"149","10":"0"},{"1":"291","2":"m","3":"9/23/34","4":"12","5":"2","6":"35250","7":"15750","8":"78","9":"387","10":"0"},{"1":"292","2":"m","3":"5/7/63","4":"14","5":"1","6":"25950","7":"15000","8":"78","9":"53","10":"0"},{"1":"293","2":"m","3":"9/19/65","4":"15","5":"1","6":"25050","7":"14250","8":"78","9":"24","10":"0"},{"1":"294","2":"m","3":"10/10/68","4":"12","5":"1","6":"26700","7":"12750","8":"78","9":"25","10":"0"},{"1":"295","2":"m","3":"8/20/32","4":"8","5":"1","6":"24000","7":"15750","8":"78","9":"476","10":"0"},{"1":"296","2":"m","3":"2/12/64","4":"12","5":"1","6":"26850","7":"15000","8":"78","9":"48","10":"0"},{"1":"297","2":"f","3":"4/16/42","4":"12","5":"1","6":"23400","7":"15300","8":"78","9":"209","10":"0"},{"1":"298","2":"f","3":"8/24/66","4":"12","5":"1","6":"24600","7":"13500","8":"78","9":"47","10":"0"},{"1":"299","2":"f","3":"5/11/65","4":"15","5":"1","6":"32550","7":"18000","8":"78","9":"6","10":"0"},{"1":"300","2":"m","3":"5/26/60","4":"16","5":"1","6":"26550","7":"15000","8":"78","9":"105","10":"1"},{"1":"301","2":"m","3":"8/4/68","4":"12","5":"1","6":"31500","7":"13500","8":"78","9":"7","10":"1"},{"1":"302","2":"m","3":"9/28/39","4":"8","5":"1","6":"22350","7":"15000","8":"78","9":"320","10":"1"},{"1":"303","2":"m","3":"2/10/38","4":"12","5":"2","6":"35250","7":"15750","8":"78","9":"281","10":"1"},{"1":"304","2":"f","3":"9/28/45","4":"15","5":"1","6":"25800","7":"13500","8":"78","9":"51","10":"1"},{"1":"305","2":"m","3":"10/25/41","4":"12","5":"2","6":"30750","7":"15750","8":"77","9":"317","10":"0"},{"1":"306","2":"m","3":"4/5/66","4":"15","5":"1","6":"30750","7":"16500","8":"77","9":"41","10":"0"},{"1":"307","2":"m","3":"7/24/45","4":"16","5":"3","6":"50000","7":"32490","8":"77","9":"264","10":"0"},{"1":"308","2":"m","3":"2/1/63","4":"15","5":"1","6":"34500","7":"18000","8":"77","9":"63","10":"0"},{"1":"309","2":"m","3":"7/19/64","4":"15","5":"1","6":"26250","7":"15750","8":"77","9":"38","10":"0"},{"1":"310","2":"m","3":"3/23/64","4":"16","5":"1","6":"44875","7":"21240","8":"77","9":"22","10":"0"},{"1":"311","2":"f","3":"2/15/51","4":"12","5":"1","6":"22500","7":"12000","8":"77","9":"63","10":"0"},{"1":"312","2":"f","3":"3/12/63","4":"12","5":"1","6":"25650","7":"14250","8":"77","9":"64","10":"0"},{"1":"313","2":"f","3":"10/25/69","4":"12","5":"1","6":"21300","7":"11250","8":"77","9":"0","10":"0"},{"1":"314","2":"f","3":"11/24/66","4":"12","5":"1","6":"29850","7":"13500","8":"77","9":"38","10":"0"},{"1":"315","2":"f","3":"9/19/69","4":"12","5":"1","6":"34500","7":"12150","8":"77","9":"4","10":"0"},{"1":"316","2":"m","3":"1/14/60","4":"15","5":"1","6":"27750","7":"15000","8":"77","9":"52","10":"1"},{"1":"317","2":"m","3":"2/27/69","4":"12","5":"1","6":"27750","7":"11550","8":"77","9":"12","10":"1"},{"1":"318","2":"m","3":"2/19/61","4":"16","5":"3","6":"48750","7":"21990","8":"76","9":"61","10":"0"},{"1":"319","2":"m","3":"3/2/66","4":"15","5":"1","6":"43410","7":"15750","8":"76","9":"12","10":"0"},{"1":"320","2":"m","3":"11/10/36","4":"12","5":"1","6":"22050","7":"15000","8":"76","9":"385","10":"0"},{"1":"321","2":"f","3":"10/26/53","4":"12","5":"1","6":"22050","7":"12000","8":"76","9":"6","10":"0"},{"1":"322","2":"f","3":"3/2/38","4":"12","5":"1","6":"22500","7":"14250","8":"76","9":"90","10":"0"},{"1":"323","2":"f","3":"5/13/67","4":"15","5":"1","6":"25500","7":"12000","8":"76","9":"7","10":"0"},{"1":"324","2":"f","3":"10/14/66","4":"12","5":"1","6":"29160","7":"15000","8":"76","9":"22","10":"0"},{"1":"325","2":"f","3":"11/4/34","4":"8","5":"1","6":"16800","7":"10200","8":"76","9":"76","10":"0"},{"1":"326","2":"m","3":"7/24/58","4":"8","5":"2","6":"29550","7":"15750","8":"76","9":"144","10":"1"},{"1":"327","2":"m","3":"3/2/65","4":"12","5":"1","6":"26700","7":"15750","8":"76","9":"18","10":"1"},{"1":"328","2":"m","3":"10/25/52","4":"18","5":"3","6":"55000","7":"32490","8":"75","9":"125","10":"0"},{"1":"329","2":"m","3":"8/24/58","4":"18","5":"3","6":"62500","7":"34980","8":"75","9":"74","10":"0"},{"1":"330","2":"m","3":"5/9/59","4":"15","5":"1","6":"27300","7":"17250","8":"75","9":"132","10":"0"},{"1":"331","2":"f","3":"2/4/42","4":"12","5":"1","6":"24450","7":"12000","8":"75","9":"144","10":"0"},{"1":"332","2":"f","3":"5/10/64","4":"16","5":"1","6":"33000","7":"18000","8":"75","9":"26","10":"0"},{"1":"333","2":"f","3":"1/26/65","4":"15","5":"1","6":"37050","7":"18000","8":"75","9":"5","10":"0"},{"1":"334","2":"f","3":"5/9/66","4":"12","5":"1","6":"24450","7":"10950","8":"75","9":"32","10":"1"},{"1":"335","2":"m","3":"2/26/30","4":"8","5":"2","6":"31950","7":"15750","8":"74","9":"408","10":"0"},{"1":"336","2":"m","3":"1/10/64","4":"16","5":"3","6":"47250","7":"21240","8":"74","9":"45","10":"0"},{"1":"337","2":"f","3":"1/27/70","4":"12","5":"1","6":"26100","7":"11550","8":"74","9":"2","10":"0"},{"1":"338","2":"f","3":"8/12/38","4":"8","5":"1","6":"15900","7":"10200","8":"74","9":"43","10":"0"},{"1":"339","2":"f","3":"11/7/42","4":"8","5":"1","6":"23700","7":"10650","8":"74","9":"281","10":"0"},{"1":"340","2":"f","3":"5/6/34","4":"8","5":"1","6":"21750","7":"12450","8":"74","9":"318","10":"0"},{"1":"341","2":"m","3":"1/20/45","4":"12","5":"3","6":"59400","7":"33750","8":"74","9":"272","10":"1"},{"1":"342","2":"f","3":"6/1/48","4":"12","5":"1","6":"24450","7":"14250","8":"74","9":"117","10":"1"},{"1":"343","2":"m","3":"6/9/53","4":"16","5":"3","6":"103500","7":"60000","8":"73","9":"150","10":"0"},{"1":"344","2":"m","3":"10/13/63","4":"12","5":"1","6":"35700","7":"16500","8":"73","9":"72","10":"0"},{"1":"345","2":"f","3":"5/5/69","4":"12","5":"1","6":"22200","7":"16500","8":"73","9":"7","10":"0"},{"1":"346","2":"f","3":"8/16/68","4":"15","5":"1","6":"22950","7":"13950","8":"73","9":"22","10":"0"},{"1":"347","2":"f","3":"8/10/44","4":"12","5":"1","6":"23100","7":"12000","8":"73","9":"228","10":"0"},{"1":"348","2":"f","3":"6/11/62","4":"16","5":"3","6":"56750","7":"30000","8":"73","9":"15","10":"0"},{"1":"349","2":"f","3":"3/22/38","4":"17","5":"1","6":"29100","7":"12750","8":"73","9":"375","10":"0"},{"1":"350","2":"f","3":"4/21/39","4":"12","5":"1","6":"37650","7":"15750","8":"73","9":"132","10":"0"},{"1":"351","2":"f","3":"1/27/66","4":"12","5":"1","6":"27900","7":"13500","8":"73","9":"32","10":"0"},{"1":"352","2":"f","3":"11/26/33","4":"8","5":"1","6":"21150","7":"12000","8":"73","9":"159","10":"0"},{"1":"353","2":"m","3":"3/10/55","4":"12","5":"2","6":"31200","7":"15750","8":"73","9":"155","10":"1"},{"1":"354","2":"f","3":"5/8/46","4":"12","5":"1","6":"20550","7":"11250","8":"73","9":"154","10":"1"},{"1":"355","2":"m","3":"5/19/61","4":"15","5":"1","6":"25950","7":"17250","8":"72","9":"83","10":"0"},{"1":"356","2":"m","3":"11/10/65","4":"15","5":"1","6":"28350","7":"15000","8":"72","9":"48","10":"0"},{"1":"357","2":"f","3":"1/18/32","4":"8","5":"1","6":"17700","7":"10200","8":"72","9":"184","10":"0"},{"1":"358","2":"f","3":"4/11/44","4":"15","5":"1","6":"23550","7":"13500","8":"72","9":"49","10":"0"},{"1":"359","2":"f","3":"6/12/41","4":"12","5":"1","6":"19950","7":"10200","8":"72","9":"56","10":"0"},{"1":"360","2":"f","3":"8/11/68","4":"12","5":"1","6":"29400","7":"15300","8":"72","9":"30","10":"0"},{"1":"361","2":"f","3":"6/9/66","4":"12","5":"1","6":"28800","7":"13950","8":"72","9":"18","10":"0"},{"1":"362","2":"f","3":"4/8/37","4":"8","5":"1","6":"16950","7":"10200","8":"72","9":"319","10":"0"},{"1":"363","2":"m","3":"6/3/54","4":"16","5":"1","6":"35700","7":"18000","8":"72","9":"138","10":"1"},{"1":"364","2":"f","3":"3/26/47","4":"12","5":"1","6":"17400","7":"10200","8":"72","9":"116","10":"1"},{"1":"365","2":"f","3":"10/16/48","4":"8","5":"1","6":"21450","7":"10200","8":"72","9":"194","10":"1"},{"1":"366","2":"f","3":"3/21/61","4":"12","5":"1","6":"24750","7":"12000","8":"72","9":"68","10":"1"},{"1":"367","2":"f","3":"5/22/42","4":"12","5":"1","6":"16950","7":"10200","8":"72","9":"271","10":"1"},{"1":"368","2":"f","3":"7/20/43","4":"12","5":"1","6":"26100","7":"13500","8":"72","9":"169","10":"1"},{"1":"369","2":"m","3":"11/14/67","4":"14","5":"1","6":"28050","7":"15000","8":"71","9":"15","10":"0"},{"1":"370","2":"f","3":"1/20/63","4":"16","5":"1","6":"36600","7":"18000","8":"71","9":"12","10":"0"},{"1":"371","2":"f","3":"4/5/66","4":"16","5":"3","6":"58125","7":"18000","8":"71","9":"11","10":"0"},{"1":"372","2":"m","3":"8/22/35","4":"15","5":"1","6":"21300","7":"15750","8":"70","9":"372","10":"0"},{"1":"373","2":"m","3":"10/29/49","4":"12","5":"1","6":"22500","7":"16500","8":"70","9":"216","10":"0"},{"1":"374","2":"m","3":"7/26/67","4":"15","5":"1","6":"29400","7":"15750","8":"70","9":"15","10":"0"},{"1":"375","2":"m","3":"10/8/66","4":"12","5":"1","6":"27450","7":"14700","8":"70","9":"41","10":"0"},{"1":"376","2":"m","3":"10/9/64","4":"15","5":"1","6":"29850","7":"15750","8":"70","9":"48","10":"0"},{"1":"377","2":"m","3":"11/29/65","4":"15","5":"1","6":"25350","7":"15750","8":"70","9":"56","10":"0"},{"1":"378","2":"f","3":"9/21/30","4":"8","5":"1","6":"15750","7":"10200","8":"70","9":"275","10":"0"},{"1":"379","2":"f","3":"5/12/38","4":"8","5":"1","6":"19650","7":"13050","8":"70","9":"102","10":"0"},{"1":"380","2":"f","3":"2/22/41","4":"12","5":"1","6":"21000","7":"13500","8":"70","9":"82","10":"0"},{"1":"381","2":"m","3":"7/15/46","4":"17","5":"1","6":"27000","7":"18000","8":"70","9":"192","10":"1"},{"1":"382","2":"m","3":"10/20/59","4":"12","5":"1","6":"24000","7":"15750","8":"70","9":"120","10":"1"},{"1":"383","2":"m","3":"6/3/61","4":"17","5":"3","6":"78500","7":"28740","8":"70","9":"67","10":"1"},{"1":"384","2":"f","3":"11/11/55","4":"12","5":"1","6":"20850","7":"13050","8":"70","9":"127","10":"1"},{"1":"385","2":"m","3":"2010/1/30","4":"12","5":"2","6":"30000","7":"15750","8":"69","9":"348","10":"0"},{"1":"386","2":"m","3":"8/18/34","4":"8","5":"2","6":"28500","7":"15750","8":"69","9":"174","10":"0"},{"1":"387","2":"m","3":"2/3/65","4":"19","5":"3","6":"65000","7":"31980","8":"69","9":"74","10":"0"},{"1":"388","2":"m","3":"1/2/59","4":"14","5":"1","6":"30150","7":"16500","8":"69","9":"110","10":"0"},{"1":"389","2":"m","3":"4/15/59","4":"19","5":"3","6":"66875","7":"32490","8":"69","9":"81","10":"0"},{"1":"390","2":"f","3":"11/9/68","4":"15","5":"1","6":"24150","7":"13500","8":"69","9":"7","10":"0"},{"1":"391","2":"f","3":"1/12/69","4":"12","5":"1","6":"24450","7":"12450","8":"69","9":"12","10":"0"},{"1":"392","2":"f","3":"5/12/70","4":"12","5":"1","6":"21600","7":"12000","8":"69","9":"0","10":"0"},{"1":"393","2":"f","3":"6/24/69","4":"12","5":"1","6":"27900","7":"12450","8":"69","9":"0","10":"0"},{"1":"394","2":"f","3":"2/4/70","4":"8","5":"1","6":"29100","7":"12450","8":"69","9":"17","10":"0"},{"1":"395","2":"f","3":"3/9/70","4":"12","5":"1","6":"22650","7":"11250","8":"69","9":"2","10":"0"},{"1":"396","2":"f","3":"8/17/70","4":"12","5":"1","6":"20850","7":"11250","8":"69","9":"0","10":"0"},{"1":"397","2":"f","3":"1/17/70","4":"12","5":"1","6":"22950","7":"12300","8":"69","9":"5","10":"0"},{"1":"398","2":"f","3":"11/21/70","4":"12","5":"1","6":"30600","7":"12450","8":"69","9":"5","10":"0"},{"1":"399","2":"f","3":"2/6/70","4":"12","5":"1","6":"20400","7":"11250","8":"69","9":"0","10":"0"},{"1":"400","2":"f","3":"8/6/69","4":"12","5":"1","6":"23850","7":"12750","8":"69","9":"20","10":"0"},{"1":"401","2":"f","3":"3/14/70","4":"12","5":"1","6":"22800","7":"11250","8":"69","9":"0","10":"0"},{"1":"402","2":"f","3":"2/7/70","4":"12","5":"1","6":"20700","7":"11250","8":"69","9":"2","10":"0"},{"1":"403","2":"f","3":"4/28/70","4":"12","5":"1","6":"21300","7":"11250","8":"69","9":"3","10":"1"},{"1":"404","2":"f","3":"5/1/53","4":"12","5":"1","6":"24300","7":"15000","8":"69","9":"121","10":"1"},{"1":"405","2":"f","3":"7/12/44","4":"12","5":"1","6":"19650","7":"13950","8":"69","9":"133","10":"1"},{"1":"406","2":"m","3":"10/5/65","4":"17","5":"3","6":"60000","7":"32490","8":"68","9":"17","10":"0"},{"1":"407","2":"m","3":"9/6/65","4":"15","5":"1","6":"30300","7":"15750","8":"68","9":"55","10":"0"},{"1":"408","2":"m","3":"2/12/64","4":"19","5":"3","6":"61250","7":"33000","8":"68","9":"9","10":"0"},{"1":"409","2":"m","3":"11/21/62","4":"19","5":"1","6":"36000","7":"19500","8":"68","9":"21","10":"0"},{"1":"410","2":"f","3":"1/9/42","4":"8","5":"1","6":"25200","7":"18750","8":"68","9":"344","10":"0"},{"1":"411","2":"f","3":"8/21/31","4":"12","5":"1","6":"16200","7":"10200","8":"68","9":"180","10":"0"},{"1":"412","2":"f","3":"6/16/70","4":"12","5":"1","6":"22800","7":"11250","8":"68","9":"2","10":"0"},{"1":"413","2":"f","3":"3/13/66","4":"16","5":"3","6":"43500","7":"19500","8":"68","9":"11","10":"0"},{"1":"414","2":"m","3":"1/8/61","4":"8","5":"2","6":"30300","7":"15750","8":"68","9":"155","10":"1"},{"1":"415","2":"m","3":"5/2/63","4":"15","5":"1","6":"31950","7":"15750","8":"68","9":"70","10":"1"},{"1":"416","2":"m","3":"1/16/65","4":"15","5":"1","6":"35250","7":"13500","8":"67","9":"6","10":"0"},{"1":"417","2":"m","3":"7/22/67","4":"15","5":"1","6":"37800","7":"15000","8":"67","9":"36","10":"0"},{"1":"418","2":"m","3":"6/5/65","4":"15","5":"1","6":"31200","7":"15750","8":"67","9":"46","10":"0"},{"1":"419","2":"m","3":"10/20/64","4":"15","5":"1","6":"29400","7":"16500","8":"67","9":"68","10":"0"},{"1":"420","2":"m","3":"7/16/57","4":"19","5":"3","6":"70000","7":"35040","8":"67","9":"75","10":"0"},{"1":"421","2":"m","3":"11/1/61","4":"15","5":"1","6":"33900","7":"15750","8":"67","9":"96","10":"0"},{"1":"422","2":"m","3":"7/20/63","4":"15","5":"1","6":"27150","7":"16500","8":"67","9":"78","10":"0"},{"1":"423","2":"f","3":"4/26/36","4":"12","5":"1","6":"22200","7":"13800","8":"67","9":"196","10":"0"},{"1":"424","2":"f","3":"7/6/66","4":"15","5":"1","6":"31350","7":"11100","8":"67","9":"47","10":"0"},{"1":"425","2":"f","3":"1/26/42","4":"12","5":"1","6":"20850","7":"13500","8":"67","9":"181","10":"0"},{"1":"426","2":"m","3":"10/27/52","4":"16","5":"1","6":"33300","7":"17490","8":"67","9":"120","10":"1"},{"1":"427","2":"m","3":"4/21/42","4":"8","5":"1","6":"26250","7":"16050","8":"67","9":"97","10":"1"},{"1":"428","2":"m","3":"2/28/64","4":"15","5":"1","6":"31950","7":"15750","8":"67","9":"58","10":"1"},{"1":"429","2":"m","3":"8/13/46","4":"8","5":"2","6":"30000","7":"15750","8":"67","9":"305","10":"1"},{"1":"430","2":"m","3":"4/29/56","4":"19","5":"3","6":"66250","7":"34980","8":"67","9":"99","10":"1"},{"1":"431","2":"m","3":"1/15/59","4":"18","5":"3","6":"86250","7":"45000","8":"66","9":"50","10":"0"},{"1":"432","2":"m","3":"3/12/64","4":"12","5":"1","6":"30750","7":"15000","8":"66","9":"56","10":"0"},{"1":"433","2":"m","3":"11/15/66","4":"12","5":"1","6":"33540","7":"15750","8":"66","9":"47","10":"0"},{"1":"434","2":"m","3":"11/16/66","4":"16","5":"1","6":"34950","7":"20250","8":"66","9":"55","10":"0"},{"1":"435","2":"m","3":"5/24/64","4":"15","5":"1","6":"40350","7":"16500","8":"66","9":"80","10":"0"},{"1":"436","2":"m","3":"5/27/65","4":"12","5":"1","6":"30270","7":"15750","8":"66","9":"80","10":"0"},{"1":"437","2":"m","3":"9/4/33","4":"8","5":"1","6":"26250","7":"16050","8":"66","9":"264","10":"0"},{"1":"438","2":"m","3":"10/11/64","4":"15","5":"1","6":"32400","7":"15000","8":"66","9":"64","10":"0"},{"1":"439","2":"f","3":"6/25/70","4":"12","5":"1","6":"20400","7":"11250","8":"66","9":"0","10":"0"},{"1":"440","2":"f","3":"11/10/47","4":"8","5":"1","6":"24150","7":"12750","8":"66","9":"96","10":"0"},{"1":"441","2":"f","3":"8/2/49","4":"15","5":"1","6":"23850","7":"13500","8":"66","9":"122","10":"0"},{"1":"442","2":"f","3":"9/18/68","4":"12","5":"1","6":"29700","7":"13500","8":"66","9":"26","10":"0"},{"1":"443","2":"f","3":"2002/10/29","4":"8","5":"1","6":"21600","7":"13500","8":"66","9":"228","10":"0"},{"1":"444","2":"f","3":"9/16/61","4":"12","5":"1","6":"24450","7":"15750","8":"66","9":"87","10":"0"},{"1":"445","2":"m","3":"8/4/63","4":"15","5":"1","6":"28050","7":"16500","8":"66","9":"84","10":"1"},{"1":"446","2":"m","3":"8/3/58","4":"16","5":"3","6":"100000","7":"44100","8":"66","9":"128","10":"1"},{"1":"447","2":"m","3":"7/2/61","4":"15","5":"1","6":"49000","7":"20550","8":"66","9":"86","10":"1"},{"1":"448","2":"f","3":"6/5/33","4":"12","5":"1","6":"16350","7":"10200","8":"66","9":"163","10":"1"},{"1":"449","2":"m","3":"1/2/66","4":"16","5":"3","6":"70000","7":"21750","8":"65","9":"19","10":"0"},{"1":"450","2":"m","3":"7/21/54","4":"19","5":"3","6":"55000","7":"34980","8":"65","9":"129","10":"0"},{"1":"451","2":"m","3":"7/19/69","4":"15","5":"1","6":"28500","7":"14250","8":"65","9":"20","10":"0"},{"1":"452","2":"m","3":"8/13/53","4":"12","5":"1","6":"28800","7":"18000","8":"65","9":"210","10":"0"},{"1":"453","2":"m","3":"2008/7/30","4":"15","5":"1","6":"24450","7":"15750","8":"65","9":"338","10":"0"},{"1":"454","2":"m","3":"7/28/65","4":"19","5":"3","6":"90625","7":"31250","8":"65","9":"18","10":"0"},{"1":"455","2":"m","3":"1/17/64","4":"16","5":"3","6":"43650","7":"19500","8":"65","9":"19","10":"0"},{"1":"456","2":"m","3":"10/17/59","4":"19","5":"3","6":"75000","7":"42510","8":"65","9":"54","10":"0"},{"1":"457","2":"m","3":"5/27/68","4":"15","5":"1","6":"31650","7":"14250","8":"65","9":"10","10":"0"},{"1":"458","2":"m","3":"7/6/65","4":"19","5":"3","6":"61875","7":"28740","8":"65","9":"26","10":"0"},{"1":"459","2":"f","3":"2/10/71","4":"12","5":"1","6":"21750","7":"11250","8":"65","9":"0","10":"0"},{"1":"460","2":"f","3":"8/12/69","4":"12","5":"1","6":"22500","7":"12750","8":"65","9":"24","10":"0"},{"1":"461","2":"f","3":"11/8/43","4":"8","5":"1","6":"21600","7":"13500","8":"65","9":"173","10":"0"},{"1":"462","2":"f","3":"10/18/63","4":"16","5":"3","6":"34410","7":"19500","8":"65","9":"79","10":"0"},{"1":"463","2":"f","3":"10/15/34","4":"15","5":"1","6":"20700","7":"14250","8":"65","9":"241","10":"0"},{"1":"464","2":"m","3":"3/20/62","4":"19","5":"3","6":"47550","7":"33000","8":"64","9":"27","10":"0"},{"1":"465","2":"m","3":"7/20/62","4":"12","5":"1","6":"33900","7":"16500","8":"64","9":"106","10":"0"},{"1":"466","2":"f","3":"6/15/48","4":"12","5":"1","6":"23400","7":"13500","8":"64","9":"198","10":"0"},{"1":"467","2":"f","3":"8/18/67","4":"16","5":"1","6":"32850","7":"19500","8":"64","9":"20","10":"0"},{"1":"468","2":"f","3":"11/28/65","4":"16","5":"3","6":"55750","7":"19980","8":"64","9":"36","10":"0"},{"1":"469","2":"f","3":"6/1/64","4":"15","5":"1","6":"25200","7":"13950","8":"64","9":"57","10":"0"},{"1":"470","2":"m","3":"1/22/64","4":"12","5":"1","6":"26250","7":"15750","8":"64","9":"69","10":"1"},{"1":"471","2":"m","3":"8/3/66","4":"15","5":"1","6":"26400","7":"15750","8":"64","9":"32","10":"1"},{"1":"472","2":"m","3":"2/21/66","4":"15","5":"1","6":"39150","7":"15750","8":"63","9":"46","10":"0"},{"1":"473","2":"f","3":"11/25/37","4":"12","5":"1","6":"21450","7":"12750","8":"63","9":"139","10":"0"},{"1":"474","2":"f","3":"11/5/68","4":"12","5":"1","6":"29400","7":"14250","8":"63","9":"9","10":"0"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
<p>从上表我们可以看出，该数据共有9个变量，其中分类变量有性别（男性或者女性），是否是少数人种（是或者否），连续型变量有工资薪水，起始工资等，变量种类挺多需要进一步分析。</p>
</div>
<div id="可视化分析探索" class="section level2">
<h2>可视化分析探索</h2>
<p>首先进行因子化处理。</p>
<pre class="r"><code>data$gender&lt;-as.factor(data$gender)
data$minority&lt;-as.factor(data$minority)
data$educ&lt;-as.factor(data$educ)
data$jobcat&lt;-as.factor(data$jobcat)</code></pre>
<div id="收入与性别分类箱线图" class="section level3">
<h3>收入与性别分类箱线图</h3>
<pre class="r"><code>ggplot(data = data,aes(x=gender,y=salary))+geom_jitter(alpha=.35,color=&#39;#4169E1&#39;,size=2.2)+geom_boxplot(alpha=.7,color=&#39;#000080&#39;)+stat_summary(fun.y=&quot;mean&quot;,geom=&quot;point&quot;,color=&quot;#000080&quot;,shape=6,size=3.5)+theme(axis.title.y=element_text(size=15))+theme(axis.title.x=element_text(size=15))+theme(axis.text.y=element_text(size=15))+theme(axis.text.x=element_text(size=15))</code></pre>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-28-1.png" width="672" /></p>
<p>从收入与性别分类箱线图可以看出，男性的收入整体显著比女性高。女性收入较为集中，男性收入的分散程度大于女性。</p>
</div>
<div id="收入与是否少数族裔箱线图" class="section level3">
<h3>收入与是否少数族裔箱线图</h3>
<pre class="r"><code>ggplot(data = data,aes(x=minority,y=salary))+geom_jitter(alpha=.35,color=&#39;#4169E1&#39;,size=2.2)+geom_boxplot(alpha=.7,color=&#39;#000080&#39;)+stat_summary(fun.y=&quot;mean&quot;,geom=&quot;point&quot;,color=&quot;#000080&quot;,shape=6,size=3.5)+theme(axis.title.y=element_text(size=15))+theme(axis.title.x=element_text(size=15))+theme(axis.text.y=element_text(size=15))+theme(axis.text.x=element_text(size=15))</code></pre>
<pre><code>## Warning: `fun.y` is deprecated. Use `fun` instead.</code></pre>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-29-1.png" width="672" /></p>
<p>从收入与是否少数族裔图看出，非少数族裔的收入中位数与少数族裔的中位数的显著差别不大，但是非少数族裔的收入整体还是明显大于少数族裔的收入，说明在美国，少数族裔的收入是明显低于非少数族裔的。</p>
</div>
<div id="收入与教育年限分类箱线图" class="section level3">
<h3>收入与教育年限分类箱线图</h3>
<pre class="r"><code>ggplot(data = data,aes(x=educ,y=salary))+geom_jitter(alpha=.35,color=&#39;#4169E1&#39;,size=2.2)+geom_boxplot(alpha=.7,color=&#39;#000080&#39;)+stat_summary(fun.y=&quot;mean&quot;,geom=&quot;point&quot;,color=&quot;#000080&quot;,shape=6,size=3.5)+theme(axis.title.y=element_text(size=15))+theme(axis.title.x=element_text(size=15))+theme(axis.text.y=element_text(size=15))+theme(axis.text.x=element_text(size=15))</code></pre>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-30-1.png" width="672" /></p>
<p>通过上图可以看出，受教育年限是明显的与收入大小成正比关系。在8和12这两个阶段相差不大，但是在16和17这两个阶段相差很大，一旦受教育程度从16提升到17，其收入程度会有很大的提升。并且随着年度的增加，这种边际效益会慢慢递减。</p>
</div>
<div id="收入与职位等级分类箱线图" class="section level3">
<h3>收入与职位等级分类箱线图</h3>
<pre class="r"><code>ggplot(data = data,aes(x=jobcat,y=salary))+geom_jitter(alpha=.35,color=&#39;#4169E1&#39;,size=2.2)+geom_boxplot(alpha=.7,color=&#39;#000080&#39;)+stat_summary(fun.y=&quot;mean&quot;,geom=&quot;point&quot;,color=&quot;#000080&quot;,shape=6,size=3.5)+theme(axis.title.y=element_text(size=15))+theme(axis.title.x=element_text(size=15))+theme(axis.text.y=element_text(size=15))+theme(axis.text.x=element_text(size=15))</code></pre>
<pre><code>## Warning: `fun.y` is deprecated. Use `fun` instead.</code></pre>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-31-1.png" width="672" /></p>
<p>通过上图看出，职位等级的不同会明显提升收入水平，而在第二等级的数据十分紧密，初步推测是由于样本太小导致的，对数据中的jobcat进行计数分析如下。</p>
<pre class="r"><code>knitr::kable(data%&gt;%count(jobcat))</code></pre>
<table>
<thead>
<tr class="header">
<th align="left">jobcat</th>
<th align="right">n</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">1</td>
<td align="right">363</td>
</tr>
<tr class="even">
<td align="left">2</td>
<td align="right">27</td>
</tr>
<tr class="odd">
<td align="left">3</td>
<td align="right">84</td>
</tr>
</tbody>
</table>
<p>从上图看出，位于第二等级的样本明显小于其他两个等级，所以导致箱线图过于紧密。</p>
</div>
<div id="受教育年限与性别关系" class="section level3">
<h3>受教育年限与性别关系</h3>
<pre class="r"><code>data2&lt;-read.csv(&quot;Employee.csv&quot;,header = T)#读取没有因子化的数据
ggplot(data2,aes(x=educ,fill=gender))+geom_histogram(position = &quot;identity&quot;,alpha=0.6,bins = 25)+theme(axis.title.y=element_text(size=15))+theme(axis.title.x=element_text(size=15))+theme(axis.text.y=element_text(size=15))+theme(axis.text.x=element_text(size=15))</code></pre>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-33-1.png" width="672" /></p>
<p>从上图看出，在搜集到的数据中，男性的受教育程度明显的多于女性，这也与受教育程度越高收入越高的事实相对应。</p>
</div>
<div id="工作时间与性别关系图" class="section level3">
<h3>工作时间与性别关系图</h3>
<pre class="r"><code>ggplot(data2,aes(x=jobtime,fill=gender))+geom_histogram(position = &quot;identity&quot;,alpha=0.6,bins = 25)+theme(axis.title.y=element_text(size=15))+theme(axis.title.x=element_text(size=15))+theme(axis.text.y=element_text(size=15))+theme(axis.text.x=element_text(size=15))</code></pre>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-34-1.png" width="672" /></p>
<p>从上图可以看出女性的工作市场在85一周之前是相对比男性多，但是在每周85之后是明显的少于男性工作时长。这也许是因为男性从事的工作的时间长度明显大于女性。</p>
</div>
<div id="不同起始薪资与收入的关系" class="section level3">
<h3>不同起始薪资与收入的关系</h3>
<pre class="r"><code>ggplot(data = data2,aes(x = salbegin))+geom_histogram(binwidth = 500,color = &quot;blue&quot;)+geom_freqpoly(mapping = aes(x=salary),binwidth = 500,color = &quot;red&quot;)</code></pre>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-35-1.png" width="672" /></p>
<p>上图纵轴是计数，横轴是起始薪资和当前薪资。直方图代表起始薪资，折线图代表现在的薪资。从上图看出，基本上当前的薪资都会比起始薪资高，并且数据都是在峰值左边较为聚集，在峰值右边明显的分散。</p>
</div>
</div>
<div id="薪资数据建模分析" class="section level2">
<h2>薪资数据建模分析。</h2>
<p>通过之前的描述分析我们大致对数据有了初步的认识和判断，接着对数据进行建模分析。在这个问题中，薪资为因变量，自变量中含有因子类型的数据。首先使用传统的线性回归建立模型</p>
<pre class="r"><code>options(scipen = 200)
data3&lt;-read.csv(&quot;Employee.csv&quot;,header = T)
data3$gender&lt;-as.factor(data3$gender)#将性别转化为因子型
data3$minority&lt;-as.factor(data3$minority)#将少数民族转化为因子型
model1&lt;-lm(salary~educ+jobcat+salbegin+jobtime+prevexp+minority+gender,data=data3)
summary(model1)</code></pre>
<pre><code>## 
## Call:
## lm(formula = salary ~ educ + jobcat + salbegin + jobtime + prevexp + 
##     minority + gender, data = data3)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -22901  -3159   -744   2621  46291 
## 
## Coefficients:
##                 Estimate   Std. Error t value             Pr(&gt;|t|)    
## (Intercept) -13610.92441   3007.16431  -4.526       0.000007634730 ***
## educ           470.05170    153.56653   3.061              0.00233 ** 
## jobcat        5760.34182    621.45145   9.269 &lt; 0.0000000000000002 ***
## salbegin         1.31956      0.07011  18.821 &lt; 0.0000000000000002 ***
## jobtime        149.98267     31.32723   4.788       0.000002270406 ***
## prevexp        -20.94984      3.32098  -6.308       0.000000000656 ***
## minority1     -987.39645    784.18450  -1.259              0.20861    
## genderm       2139.92620    735.59361   2.909              0.00380 ** 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 6805 on 466 degrees of freedom
## Multiple R-squared:  0.8435, Adjusted R-squared:  0.8412 
## F-statistic: 358.9 on 7 and 466 DF,  p-value: &lt; 0.00000000000000022</code></pre>
<p>将薪资作为自变量，受教育年限，职位等级，起始薪资，工作经验，工作时长，性别，作为因变量，建模线性回归模型。最终的模型为<span class="math inline">\(y=-13610.92+470.05*educ+5760*jobcat+1.31*salbegin+149.98*jobtime-20.94*prevexp-987.39*minority+2139.92*gender\)</span>。
但是发现模型的minority变量没有通过检验，不显著，因此考虑剔除该变量。</p>
<div id="模型的检验" class="section level3">
<h3>模型的检验</h3>
<pre class="r"><code>par(mfrow=c(2,2))
plot(model1,which = c(1:4))</code></pre>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-37-1.png" width="672" /></p>
<pre class="r"><code>library(equatiomatic)</code></pre>
<div id="加权最小二乘建模" class="section level4">
<h4>加权最小二乘建模</h4>
<p>通过上面四张图看出该模型有一定的异方差性，需要进行加权建模。这里我们将权重设置为，salbegin,jobcat和jobtime三个变量的平方分之一，接着对模型进行分析。</p>
<pre class="r"><code>model2&lt;-lm(salary~educ+jobcat+salbegin+jobtime+prevexp+gender,data=data3)
resd&lt;-model2$residuals
resd&lt;-abs(resd)
summary(model2)</code></pre>
<pre><code>## 
## Call:
## lm(formula = salary ~ educ + jobcat + salbegin + jobtime + prevexp + 
##     gender, data = data3)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -22924  -3272   -670   2606  46565 
## 
## Coefficients:
##                Estimate  Std. Error t value             Pr(&gt;|t|)    
## (Intercept) -13822.1833   3004.3615  -4.601       0.000005431508 ***
## educ           471.8788    153.6559   3.071              0.00226 ** 
## jobcat        5802.3314    620.9449   9.344 &lt; 0.0000000000000002 ***
## salbegin         1.3284      0.0698  19.030 &lt; 0.0000000000000002 ***
## jobtime        148.5239     31.3254   4.741       0.000002824209 ***
## prevexp        -21.4462      3.2996  -6.500       0.000000000207 ***
## genderm       2005.0468    728.2081   2.753              0.00613 ** 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 6809 on 467 degrees of freedom
## Multiple R-squared:  0.843,  Adjusted R-squared:  0.841 
## F-statistic: 417.9 on 6 and 467 DF,  p-value: &lt; 0.00000000000000022</code></pre>
<pre class="r"><code>model3&lt;-lm(salary~educ+jobcat+salbegin+jobtime+prevexp+gender,data=data3,weights = salbegin^{-2}+jobcat^{-2}+jobtime^{-2})
summary(model3)</code></pre>
<pre><code>## 
## Call:
## lm(formula = salary ~ educ + jobcat + salbegin + jobtime + prevexp + 
##     gender, data = data3, weights = salbegin^{
##     -2
## } + jobcat^{
##     -2
## } + jobtime^{
##     -2
## })
## 
## Weighted Residuals:
##    Min     1Q Median     3Q    Max 
## -14296  -2708   -642   2020  46853 
## 
## Coefficients:
##                 Estimate   Std. Error t value             Pr(&gt;|t|)    
## (Intercept) -12406.52132   2399.42065  -5.171    0.000000346681527 ***
## educ           446.91621    121.49125   3.679             0.000262 ***
## jobcat        5055.52805    886.57803   5.702    0.000000020991222 ***
## salbegin         1.45811      0.08887  16.407 &lt; 0.0000000000000002 ***
## jobtime        121.53179     23.96567   5.071    0.000000571490307 ***
## prevexp        -18.95859      2.54655  -7.445    0.000000000000472 ***
## genderm       1511.88296    553.91437   2.729             0.006584 ** 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 4656 on 467 degrees of freedom
## Multiple R-squared:  0.717,  Adjusted R-squared:  0.7134 
## F-statistic: 197.2 on 6 and 467 DF,  p-value: &lt; 0.00000000000000022</code></pre>
<pre class="r"><code>#计算model3残差
e&lt;-resid(model3)
abse&lt;-abs(e)
y.fit&lt;-predict(model3)
biaozhunhua&lt;-scale(e)
sqrtcancha&lt;-sqrt(biaozhunhua)</code></pre>
<pre><code>## Warning in sqrt(biaozhunhua): 产生了NaNs</code></pre>
<pre class="r"><code>plot(sqrtcancha~y.fit)</code></pre>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-39-1.png" width="672" /></p>
<p>模型的表达式如下
<span class="math display">\[
\operatorname{salary} = \alpha + \beta_{1}(\operatorname{educ}) + \beta_{2}(\operatorname{jobcat}) + \beta_{3}(\operatorname{salbegin}) + \beta_{4}(\operatorname{jobtime}) + \beta_{5}(\operatorname{prevexp}) + \beta_{6}(\operatorname{gender}_{\operatorname{m}}) + \epsilon
\]</span></p>
</div>
</div>
<div id="进行加权和未进行加权比较" class="section level3 tabset">
<h3>进行加权和未进行加权比较</h3>
<div id="未进行加权建模图" class="section level4">
<h4>未进行加权建模图</h4>
<p>(</p>
<pre class="r"><code>par(mfrow=c(2,2))
plot(model2,which = c(1:4),caption = &quot;model2未加权&quot;)</code></pre>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-40-1.png" width="672" />
)</p>
</div>
<div id="进行加权建模图" class="section level4">
<h4>进行加权建模图</h4>
<p>(</p>
<pre class="r"><code>par(mfrow=c(2,2))
plot(model3,which = c(1:4),caption = &quot;model3加权建模&quot;)</code></pre>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-41-1.png" width="672" />
)</p>
<p>通过上图看出,通过加权可以解决模型的异方差性。</p>
</div>
</div>
<div id="检验多重共线性" class="section level3">
<h3>检验多重共线性</h3>
<pre class="r"><code>library(car)</code></pre>
<pre><code>## 载入需要的程辑包：carData</code></pre>
<pre><code>## 
## 载入程辑包：&#39;car&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:dplyr&#39;:
## 
##     recode</code></pre>
<pre><code>## The following object is masked from &#39;package:purrr&#39;:
## 
##     some</code></pre>
<pre class="r"><code>round(vif(model3),2)</code></pre>
<pre><code>##     educ   jobcat salbegin  jobtime  prevexp   gender 
##     1.53     1.54     2.32     1.02     1.11     1.33</code></pre>
<p>上述变量都小于10并且接近1，说明没有多重共线性问题。</p>
</div>
</div>
<div id="变量选择" class="section level2">
<h2>变量选择</h2>
<p>在这里其实我感觉是不需要再进行变量选择的，因为模型已经解决了异方差性和多重共线性问题。但是课件上面讲了这些，还是做一下。</p>
<pre class="r"><code>modelstep&lt;-step(model3,direction = &quot;both&quot;)#使用逐步回归法</code></pre>
<pre><code>## Start:  AIC=8013.64
## salary ~ educ + jobcat + salbegin + jobtime + prevexp + gender
## 
##            Df  Sum of Sq         RSS    AIC
## &lt;none&gt;                   10123086798 8013.6
## - gender    1  161490564 10284577362 8019.1
## - educ      1  293331236 10416418034 8025.2
## - jobtime   1  557438393 10680525190 8037.0
## - jobcat    1  704847552 10827934349 8043.5
## - prevexp   1 1201449131 11324535929 8064.8
## - salbegin  1 5835365806 15958452603 8227.4</code></pre>
<pre class="r"><code>summary(modelstep)</code></pre>
<pre><code>## 
## Call:
## lm(formula = salary ~ educ + jobcat + salbegin + jobtime + prevexp + 
##     gender, data = data3, weights = salbegin^{
##     -2
## } + jobcat^{
##     -2
## } + jobtime^{
##     -2
## })
## 
## Weighted Residuals:
##    Min     1Q Median     3Q    Max 
## -14296  -2708   -642   2020  46853 
## 
## Coefficients:
##                 Estimate   Std. Error t value             Pr(&gt;|t|)    
## (Intercept) -12406.52132   2399.42065  -5.171    0.000000346681527 ***
## educ           446.91621    121.49125   3.679             0.000262 ***
## jobcat        5055.52805    886.57803   5.702    0.000000020991222 ***
## salbegin         1.45811      0.08887  16.407 &lt; 0.0000000000000002 ***
## jobtime        121.53179     23.96567   5.071    0.000000571490307 ***
## prevexp        -18.95859      2.54655  -7.445    0.000000000000472 ***
## genderm       1511.88296    553.91437   2.729             0.006584 ** 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 4656 on 467 degrees of freedom
## Multiple R-squared:  0.717,  Adjusted R-squared:  0.7134 
## F-statistic: 197.2 on 6 and 467 DF,  p-value: &lt; 0.00000000000000022</code></pre>
<p>上面是使用逐步回归法模型。其实可以使用这个来消除多重共线性等问题。</p>
</div>
<div id="总结" class="section level2">
<h2>总结</h2>
<p>通过各种方法，解决了异方差性和多重共线性，本文最终建立的模型如下：
<span class="math display">\[
salary=-12406.52+446.91*educ+5055.52*jobcat+1.45*salbegin+121.53*jobtime-18.95*prevexp+1511.88*gender
\]</span></p>
</div>
</div>
